require(testthat)

test_that("stri_split_charclass", {
   expect_identical(stri_split_charclass(character(0),"\\p{Z}"),list())
   expect_identical(stri_split_charclass(NA,NA),list(NA_character_))
   expect_identical(stri_split_charclass(NA,"\\p{Z}"),list(NA_character_))
   expect_identical(stri_split_charclass("???",NA),list(NA_character_))
   expect_identical(stri_split_charclass("???","\\p{Z}",NA),list(NA_character_))
   expect_identical(stri_split_charclass("???","\\p{Z}",2,NA),list(NA_character_))
   expect_identical(stri_split_charclass("","\\p{Z}"),list(""))
   expect_identical(stri_split_charclass("","\\p{Z}", omit_empty=TRUE),list(character(0)))
   expect_identical(stri_split_charclass("gas","\\p{Z}", n_max=0),list(character(0)))
   expect_identical(stri_split_charclass("  ","\\p{Z}"),list(c("", "", "")))
   expect_identical(stri_split_charclass("  ","\\p{Z}", omit_empty=TRUE),list(character(0)))
   expect_identical(stri_split_charclass(" a  ","\\p{Z}", omit_empty=TRUE),list("a"))
   expect_identical(stri_split_charclass("ala ma kota", "\\p{Z}"), list(c("ala", "ma", "kota")))
   expect_identical(stri_split_charclass("ala ma kota", "\\p{Z}", 0), list(character(0)))
   expect_identical(stri_split_charclass("ala ma kota", "\\p{Z}", 1), list(c("ala ma kota")))
   expect_identical(stri_split_charclass("ala ma kota", "\\p{Z}", 2), list(c("ala", "ma kota")))
   expect_identical(stri_split_charclass("a  b", "\\p{Z}"), list(c("a", "", "b")))
   expect_identical(stri_split_charclass("a  b", "\\p{Z}", omit_empty=TRUE), list(c("a", "b")))
   expect_identical(stri_split_charclass(c("a1a", "aXa"), c("\\p{N}", "\\p{Lu}")), list(c("a", "a"), c("a", "a")))
})
