require(testthat)

test_that("stri_split_regex", {
   expect_identical(stri_split_regex(character(0)," "),list())
   expect_identical(stri_split_regex(NA,NA),list(NA_character_))
   expect_identical(stri_split_regex(NA,"a"),list(NA_character_))
   expect_identical(stri_split_regex("NA",NA),list(NA_character_))
   expect_identical(stri_split_regex("NA","a",NA),list(NA_character_))
   expect_identical(stri_split_regex("NA","a",1,NA),list(NA_character_))
   expect_identical(stri_split_regex(" "," "),list(rep("",2)))
   expect_identical(stri_split_regex("","Z"),list(""))
   expect_identical(stri_split_regex("","Z", omit_empty=TRUE),list(character(0)))
   expect_identical(stri_split_regex("gas","Z", n_max=0),list(character(0)))
   expect_identical(stri_split_regex("aa","a"),list(rep("",3)))
   expect_identical(stri_split_regex("aa","a",-1L,TRUE),list(character(0)))
   expect_identical(stri_split_regex("ala ma kota 1 a","[a-z] [a-z]"),list(c("al","","ota 1 a")))
   expect_identical(stri_split_regex("ala ma kota 1 a","[a-z] [a-z]*"),list(c("al"," kot","1 a")))
   expect_identical(stri_split_regex("ala ma kota 1 a","[a-z] [a-z]+"),list(c("al"," kota 1 a")))
   expect_identical(stri_split_regex("ala ma kota 1 a","[a-z] [1-9]"),list(c("ala ma kot"," a")))
   expect_identical(stri_split_regex("ala ma kota 1 a","[a-z] [1-9]+"),list(c("ala ma kot"," a")))

   # n
   expect_identical(stri_split_regex(";123", ";", n=2), list(c("", "123")))
   expect_identical(stri_split_regex(";123", ";", n=2, omit_empty=TRUE), list("123"))
   expect_identical(stri_split_regex("123;456", ";", n=2), list(c("123", "456")))
   expect_identical(stri_split_regex("123;456;789", ";", n=2), list(c("123", "456;789")))
   expect_identical(stri_split_regex("123-456-789", "-", n=1:3),
                    list(c("123-456-789"),c("123","456-789"),c("123","456","789")))
   expect_identical(stri_split_regex("123-456-789", "[1-8]-.", n=5), list(c("12","5","89")))
})
