% kate: indent-width 2; word-wrap-column 74; syntax latex

%!TEX program = XeLaTeX
%!Rnw weave = Sweave


% TODO: stri_opts_coll alias

% sudo apt install latex-cjk-all

%
% TODO: knitr::knit("stringi_v5.Rnw", tangle=TRUE)
% TODO: remove echo=FALSE and add section titles





%  \documentclass[nojss]{jss}
\documentclass[article]{jss}
\usepackage{xltxtra}

\usepackage{thumbpdf,lmodern,xcolor}
% \usepackage{framed}
% \usepackage[utf8]{inputenc}
% \usepackage[T1]{fontenc}
% \usepackage{CJKutf8}
\usepackage{amsmath,amssymb}
\usepackage{booktabs}
\usepackage{verbatim}
\usepackage{tabularx}
% \usepackage[UTF8]{ctex}
\usepackage{xeCJK}
\usepackage{fontspec}
\usepackage{wasysym}
\setCJKmainfont{Noto Sans Mono CJK SC}
\setCJKsansfont{Noto Sans Mono CJK SC}
\setCJKmonofont{Noto Sans Mono CJK SC}
\usepackage{tipa}
% \usepackage{lmodern}
% \setmonofont{Latin Modern Mono}
% \setmonofont{Ubuntu Mono}%[Scale=0.85]
% \usepackage{alphabeta}



%% For Sweave-based articles about R packages:
%% need no \usepackage{Sweave}
%\usepackage{Sweave}
%\SweaveOpts{engine=R, eps=FALSE, keep.source = TRUE}





\author{Marek Gagolewski\\
Deakin University, Geelong, VIC 3220, Australia\\
Systems Research Institute, Polish Academy of Sciences
}
\Plainauthor{Marek Gagolewski}

%% - \title{} in title case
%% - \Plaintitle{} without LaTeX markup (if any)
%% - \Shorttitle{} with LaTeX markup (if any), used as running title
\title{\textit{stringi}: Fast and Portable\\Character String
Processing in {R}}
\Plaintitle{stringi: Fast and Portable Character String Processing in R}
\Shorttitle{\textit{stringi}: Fast and Portable Character String Processing
in {R}}

% \title in title style,
% all titles in the BibTeX file in title style.
% \section, \subsection, etc. in sentence style,



%% - \Abstract{} almost as usual
\Abstract{
Effective processing of character strings is required at various
stages of data analysis pipelines:
from data cleansing and preparation, through
information extraction, to report generation.
Pattern searching, string collation and sorting, normalisation,
transliteration, and formatting are ubiquitous in
text mining, natural language processing, and bioinformatics.
This paper discusses and demonstrates how and why \textit{stringi},
a mature {R} package for fast and portable handling of string data
based on \textit{International Components for Unicode},
should be included in each statistician's or data scientist's
repertoire to complement their  numerical computing
and data wrangling skills.
}

%% - \Keywords{} with LaTeX markup, at least one required
%% - \Plainkeywords{} without LaTeX markup (if necessary)
%% - Should be comma-separated and in sentence case.
\Keywords{\textit{stringi}, character strings, text, \textit{ICU}, Unicode,
regular expressions, data cleansing, natural language processing,
{R}}
\Plainkeywords{stringi, character strings, text, ICU, Unicode, regular
expressions, data cleansing, natural language processing, R}

\Address{
  \textbf{Marek Gagolewski}\\
  School of Information Technology\\
  Deakin University\\
  Geelong, VIC 3220, Australia\\
  \emph{and}\\
  Systems Research Institute\\
  Polish Academy of Sciences\\
  ul.~Newelska 6, 01-447 Warsaw, Poland\\
  E-mail: \email{m.gagolewski@deakin.edu.au}\\
  URL: \url{https://www.gagolewski.com/}
}

\begin{document}


\begin{verbatim}<<echo=FALSE, results="hide", message=FALSE>>=
##########################################################################
############## TODO: del me - debug only!!! ##########################################################################
options(prompt="R> ", continue="+  ")
library("knitr")
knitr::render_sweave()
#knitr::knitr_hooks$set(chunk=knitr::render_sweave())

opts_chunk$set(
#  fig.height=3.5,
#  fig.width=6,
#  dev=c("CairoPDF", "CairoSVG"),
#  out.width=NULL,
#  dpi=300,
#  dev.args=list(pointsize=11),
#  fig.show="hold",
#  fig.lp='fig:',
  tidy=FALSE,
  error=FALSE,
  autodep=TRUE,
  cache=TRUE
)

library("stringi")
stri_locale_set("en_AU")
library("stringr")
set.seed(123)

options(width=77)
options(useFancyQuotes=FALSE)
options(encoding="UTF-8")
options(digits=5)
options(max.print=99)
options(scipen=10)
options(showWarnCalls=FALSE)
#options(stringsAsFactors=FALSE) # default in R 4.0
##########################################################################
@\end{verbatim}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Introduction}\label{Sec:intro}

Stringology \citep{stringology} deals with algorithms and data structures
for character string processing \citep{speechlangproc,szpankowski}.
From the perspective of applied statistics and data science,
it is worth stressing that many interesting data sets
first come in unstructured or contaminated textual forms,
for instance when they have been fetched from different APIs
(application programming interface) or gathered
by means of web scraping techniques.

Diverse data cleansing and preparation operations
(\citealp{datacleaning,cleanr}; see also
Section~\ref{Sec:examples} below for a real-world example)
need to be applied before an analyst can begin to enjoy
an orderly and meaningful data frame, matrix, or spreadsheet being finally
at their disposal.
Activities related to information retrieval, computer vision,
bioinformatics, natural language processing, or even musicology
can also benefit from including them
in data processing pipelines \citep{speechlangproc,genome}.
% This includes string concatenation,
% substring extraction, collation, sorting, Unicode normalisation,
% transliteration, pattern matching, and date-time parsing.


% sentiment of emojis 10.1371/journal.pone.0144296
Although statisticians and data analysts are usually
very proficient in numerical computing and data wrangling,
the awareness of how crucial text operations are in the generic
data-oriented skill-set is yet to reach a more operational
level. This paper aims to fill this gap.

\bigskip
Most statistical computing ecosystems provide only a basic set of text
operations. In particular, base {R} \citep{Rproject:home}
is mostly restricted to pattern matching, string concatenation,
substring extraction, trimming, padding, wrapping,
simple character case conversion, and string collation,
see \citep[Chapter~8]{Chambers2008:SoftDA} and Table~\ref{Tab:oldstringr} below.
The \textit{stringr} package \citep{Wickham2010:stringr},
first released in November 2009, implemented an alternative, ``tidy''
API for text data processing (cleaned-up function names,
more beginner-friendly outputs, etc.;
the list of 21 functions that were available in \textit{stringr} at that
time is given in Table~\ref{Tab:oldstringr}).
The early \textit{stringr} featured a few wrappers around
a subset of its base {R} counterparts. The latter,
however -- to this day -- not only is of limited scope,
but also suffers from a number of portability issues; it may happen that
the same code can yield different results on different operating systems;
see Section~\ref{Sec:design} for some examples.


% In version 0.6.2 (dated 2012--12--06)
% of \textit{stringr}'s \texttt{README}, we read that this package:
% \begin{quote}\it
% \begin{itemize}
% \item processes factors and characters in the same way,
% \item gives functions consistent names and arguments,
% \item simplifies string operations by eliminating options that you
% don't need 95\% of the time,
% \item produces outputs than can easily be used as inputs.
% This includes ensuring that missing inputs result in missing outputs,
% and zero length inputs result in zero length outputs,
% \item completes {R}'s string handling functions with
% useful functions from other programming languages.
% % and duplicates existing API :/
% \end{itemize}
% \end{quote}

In order to significantly broaden the array of string processing
operations and assure that they are portable, in 2013 the current
author developed the open source \textit{stringi} package
(pronounced ``stringy'', IPA \textipa{[{stringi}]}).
Its API was compatible with that of early \textit{stringr}'s,
which some users found convenient. However, for the processing of text
in different locales, which are plentiful, \textit{stringi} relies
on \textit{ICU} -- \textit{International Components for Unicode}
(see \url{https://icu.unicode.org/}) -- a mature library that
fully conforms with the Unicode standard and which provides globalisation
support for a broad range of other software applications as well, from
web browsers to database systems. Services not covered by \textit{ICU}
were implemented from scratch to guarantee that they are as efficient
as possible.

Over the years, \textit{stringi} confirmed itself as robust,
production-quality software; for many years now it has been one of the
most often downloaded {R} extensions. Interestingly, in 2015 the
aforementioned \textit{stringr} package has been rewritten as a
set of wrappers around some of the \textit{stringi} functions instead of
the base {R} ones.
% \textit{stringr} currently exports \Sexpr{length(ls("package:stringr"))} objects
In Section~14.7 of \textit{{R} for Data Science}
\citep{GrolemundWickham2017:rdatascience}
we read: \textit{\textit{stringr} is useful when you're learning because
it exposes a minimal set of functions, which have been carefully picked
to handle the most common string manipulation functions. \textit{stringi},
on the other hand, is designed to be comprehensive. It contains almost
every function you might ever need: \textit{stringi} has 250 functions to
\textit{stringr}'s 49}.
Also, it is worth noting that the recently-introduced \textit{stringx}
package \citep{stringx} supplies a \textit{stringi}-based set of portable
and efficient replacements for and enhancements of the base {R}
functions.

% > sum(stri_detect(ls(envir=environment(str_detect)), regex="^str_"))  # v0.6.2
% [1] 21
% > sum(stri_detect(ls(envir=environment(str_detect)), regex="^str_"))  # v1.4.0
% [1] 45
% > sum(stri_detect(ls(envir=environment(stri_detect)), regex="^stri_"))
% [1] 242

% On the other hand, \textit{stringi} provides many more
% functions (\Sexpr{length(ls("package:stringi"))}
% vs~\Sexpr{length(ls("package:stringr"))}); some of them are
% more specialised or equipped with more control parameters
% to enable fine-tuning.

\bigskip
This paper describes the most noteworthy facilities provided by
\textit{stringi} that statisticians and data analysts may find
useful in their daily activities. We demonstrate how important it is
for a modern data scientist to be aware of the challenges
of natural language processing in the internet era:
how to force \texttt{"groß"} compare equal to \texttt{"GROSS"},
count the number of occurrences of \texttt{"AGA"} within
\texttt{"ACTGAGAGACGGGTTAGAGACT"},
make \texttt{"a13"} ordered before \texttt{"a100"}, or
convert between \texttt{"GRINNING FACE"} and \texttt{"\smiley"} forth and back.
Such operations are performed by the very \textit{ICU} itself;
we therefore believe that what follows may be of interest
to data-oriented practitioners employing {Python},
{Perl}, {Julia}, {PHP}, etc.,
as \textit{ICU} has bindings for many other languages.


Here is the outline of the paper:
\begin{itemize}
\item Section~\ref{Sec:examples} illustrates the importance of string
processing in an example data preparation activity.

\item General package design principles are outlined in
Section~\ref{Sec:design}, including the use cases of deep vectorisation,
the concepts of data flow,
and the main deviations from base {R}
(also with regards to portability and speed).

\item Basic string operations, such as computing length and width
of strings, string concatenation, extracting and replacing substrings,
are discussed in Section~\ref{Sec:basic}.

\item Section~\ref{Sec:fixed} discusses searching for fixed substrings:
counting the number of matches, locating their positions,
replacing them with other data, and splitting strings into tokens.
% detecting, extracting

\item Section~\ref{Sec:regex} details \textit{ICU} regular
expressions, which are a powerful tool for matching patterns defined in
a more abstract way, e.g., extracting numbers from text so that they can
be processed quantitatively, identifying hyperlinks, etc.
We show where \textit{ICU} is different from other libraries like \textit{PCRE};
in particular that it enables portable, Unicode-correct look-ups,
for instance, involving sequences of emojis or mathematical symbols.

\item Section~\ref{Sec:collator} deals with the locale-aware \textit{ICU}
Collator, which is  suitable for natural language processing activities;
this is where we demonstrate that text processing in different languages
or regions is governed by quite diverse rules,
deviating significantly from the US-ASCII (``C/POSIX.1'') setting.
The operations discussed therein include testing string equivalence (which can
turn out useful when we scrape data that consist of non-normalised strings,
ignorable punctuation, or accented characters) as well as arranging strings
with regards to different linear orderings.

\item Section~\ref{Sec:other} covers some other useful operations such
as text boundary analysis (for splitting text into words or sentences),
trimming, padding, and other formatting, random string generation,
character transliteration (converting between cases and alphabets,
removing diacritic marks, etc.) as well as date-time formatting and
parsing in any locale (e.g., Japanese dates in a German {R}).

\item Section~\ref{Sec:io} details on encoding conversion and detection
(which is key when reading or writing text files that are to be communicated
across different systems) as well as Unicode normalisation
(which can be useful for removing formatting
distinctions from text, e.g., superscripts or font variants).

\item Finally, Section~\ref{Sec:conclusions} concludes the paper.
\end{itemize}



This paper is by no means a substitute for the comprehensive yet much
more technical and in-depth reference manual available via a call to
\texttt{help(package="stringi")}, see also
\url{https://stringi.gagolewski.com/}. Rather, below we explain
the package's key design principles and broadly introduce the ideas and
services that help program, correct, and optimise text processing workflows.

Let us emphasise that all the below-presented illustrations,
i.e., calls to \textit{stringi} functions on different
example arguments together with the generated outputs, form an integral
part of this manuscript's text. They have been included based on
the author's experience-based belief that each "picture" (that we print
out below using a monospaced font) is worth hundreds of words.

% confirmed itself as robust,  production quality software
% yet, new features being added $\sim$ biyearly








%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\medskip
All code chunk outputs presented in this paper were obtained in
{R}~\Sexpr{paste(R.Version()[6:7], collapse=".")}.
The {R} environment itself and all the packages used herein
are available from CRAN (the Comprehensive {R} Archive Network)
at \url{https://CRAN.R-project.org/}.
In particular, \texttt{install.packages("stringi")} can be called to
fetch the object of our focus.
%Moreover, for \textit{stringr}~\Sexpr{packageVersion("stringr")}
By calling:

%%% # R CMD INSTALL stringi --preclean --configure-args='--disable-pkg-config'

\begin{verbatim}<<results="hide">>=
library("stringi")
cat(stri_info(short=TRUE))
@\end{verbatim}

\begin{verbatim}<<echo=FALSE>>=
##########################################################################
############## TODO: del me - debug only!!! ##########################################################################
stopifnot(!stringi::stri_info()$ICU.system)
stopifnot(packageVersion("stringi") >= package_version("1.7.4"))
cat(stri_wrap(stri_info(short=TRUE), 78), sep="\n")
##########################################################################
@\end{verbatim}


\noindent
we can load and attach the package's namespace
and display some basic information thereon.
Hence, below we shall be working with
\textit{stringi} \Sexpr{packageVersion("stringi")}, however, as the package's
API is considered stable, the presented material should be relevant to
any later versions.
% which has been built against the following version of the \textit{ICU}
% library and which uses the following



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Use case: Data preparation}\label{Sec:examples}

Before going into details on the broad array of facilities offered by the
\textit{stringi} package itself,
let us first demonstrate that string processing is indeed a relevant
part of statistical data analysis workflows.
What follows is a short case study where we prepare a web-scraped
data set for further processing.

Assume we wish to gather and analyse
climate data for major cities around the world based on information
downloaded from Wikipedia.
For each location from a given list of settlements (e.g.,
fetched from one of the pages linked under
\url{https://en.wikipedia.org/wiki/Lists_of_cities}),
we would like to harvest the relevant temperature and precipitation data.
Without harm in generality, let us focus on the city of Melbourne,
VIC, Australia.

The parsing of the city's~Wikipedia page
can be done by means of the functions from the
\textit{xml2} \citep{xml2}
and \textit{rvest} \citep{rvest} packages.

\begin{verbatim}<<html-example-1>>=
library("xml2")
library("rvest")
@\end{verbatim}

First, let us load and parse the {HTML} file
downloaded on 2020--09--17 (see the accompanying supplementary files):

\begin{verbatim}<<html-example-2>>=
f <- read_html("20200917_wikipedia_melbourne.html")
@\end{verbatim}

Second, we extract all \texttt{table} elements and gather them
in a list of {HTML} nodes, \texttt{all\_tables}.
We then extract the underlying raw text data and store them in a
character vector named \texttt{text\_tables}.

\begin{verbatim}<<html-example-3>>=
all_tables <- html_nodes(f, "table")
text_tables <- sapply(all_tables, html_text)
str(text_tables, nchar.max=65, vec.len=5, strict.width="wrap") # preview
@\end{verbatim}

Most~Wikipedia pages related to particular cities
include a table labelled as ``Climate data''.
We need to pinpoint it amongst all the other tables.
For this, we will rely on \textit{stringi}'s
\texttt{stri\_detect\_fixed()} function that, in the configuration
below, is used to extract the index of the relevant table.

\begin{verbatim}<<html-example-4>>=
library("stringi")
(idx <- which(stri_detect_fixed(text_tables, "climate data",
  case_insensitive=TRUE, max_count=1)))
@\end{verbatim}

Of course, the detailed description of all the facilities
brought by \textit{stringi} is covered below.
In the meantime, let us use \textit{rvest}'s \texttt{html\_table()}
to convert the above table to a data frame object.


\begin{verbatim}<<html-example-5,results="hide">>=
(x <- as.data.frame(html_table(all_tables[[idx]], fill=TRUE)))
@\end{verbatim}

\begin{verbatim}<<html-example-6,echo=FALSE>>=
##########################################################################
############## TODO: del me - debug only!!!
##########################################################################
.x <- x[c(1, 2, 3, ncol(x))]
.x[,3] <- "..."
names(.x)[3] <- "..."
print(.x)
##########################################################################
@\end{verbatim}

It is evident that this object requires some significant cleansing
and transforming before it can be subject to any statistical analyses.
First, for the sake of convenience, let us convert it to a character
matrix so that the processing of all the cells can be vectorised
(a matrix in {R} is just a single ``long'' vector,
whereas a data frame is a list of many atomic vectors).

\begin{verbatim}<<html-example-7>>=
x <- as.matrix(x)
@\end{verbatim}

The \texttt{as.numeric()} function will find the parsing of
the Unicode MINUS SIGN (U+2212, ``−'') difficult,
therefore let us call the transliterator first in order to replace it
(and other potentially problematic characters) with its simpler equivalent:

\begin{verbatim}<<html-example-8>>=
x[, ] <- stri_trans_general(x, "Publishing-Any; Any-ASCII")
@\end{verbatim}

Note that it is the first row of the matrix that defines the column names.
Moreover, the last row just gives the data source and hence may be removed.

\begin{verbatim}<<html-example-9>>=
dimnames(x) <- list(x[, 1], x[1, ])  # row, column names
x <- x[2:(nrow(x) - 1), 2:ncol(x)]   # skip 1st/last row and 1st column
x[, c(1, ncol(x))]                   # example columns
@\end{verbatim}

Commas that are used as thousands separators (commas surrounded
by digits) should be dropped:

\begin{verbatim}<<html-example-10>>=
x[, ] <- stri_replace_all_regex(x, "(?<=\\d),(?=\\d)", "")
@\end{verbatim}

The numbers and alternative units in parentheses are redundant,
therefore these should be taken care of as well:

\begin{verbatim}<<html-example-11>>=
x[, ] <- stri_replace_all_regex(x,
  "(\\d+(?:\\.\\d+)?)\\(\\d+(?:\\.\\d+)?\\)", "$1")
dimnames(x)[[1]] <- stri_replace_all_fixed(dimnames(x)[[1]],
  c(" (°F)", " (inches)"), c("", ""), vectorise_all=FALSE)
@\end{verbatim}

At last, \texttt{as.numeric()} can be used to re-interpret all the strings
as numbers:

\begin{verbatim}<<html-example-12>>=
x <- structure(as.numeric(x), dim=dim(x), dimnames=dimnames(x))
x[, c(1, 6, ncol(x))]  # example columns
@\end{verbatim}

We now have a cleansed matrix at our disposal.
We can, for instance, compute the monthly temperature ranges:

\begin{verbatim}<<html-example-13>>=
x["Record high °C", -ncol(x)] - x["Record low °C", -ncol(x)]
@\end{verbatim}

\noindent
or the average daily precipitation:

\begin{verbatim}<<html-example-14>>=
sum(x["Average rainfall mm", -ncol(x)]) / 365.25
@\end{verbatim}

\noindent
and so forth.

For the climate data on other cities, very similar operations
will need to be performed -- the whole process of scraping and cleansing data
can be automated quite easily.
The above functions are not only convenient to use, but also efficient
and portable across different platforms.



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{General design principles}\label{Sec:design}

The API of the early releases of \textit{stringi} has been designed so as
to be fairly compatible with that of the 0.6.2 version of the
\textit{stringr} package
\citep{Wickham2010:stringr} (dated 2012; see Table~\ref{Tab:oldstringr}),
with some fixes in the
consistency of the handling of missing values and zero-length vectors,
amongst others.
However, instead of being merely thin wrappers around base {R}
functions, which we have identified as not necessarily portable across
platforms and not really suitable for natural language processing tasks,
all the functionality has been implemented from the ground up,
with the use of \textit{ICU} services wherever applicable. Since the
initial release, an abundance of new features has been added
and the package can now be considered a comprehensive workhorse
for text data processing.
Note that the \textit{stringi} API is stable.
Future releases are aiming for as much backward compatibility
as possible so that other software projects can safely rely on it.


% stringr 0.6.2:
% vectorisation wrt all arguments was there with recycling
% str_c - recycling rule, but NA=="NA" and character(0) fail.
% str_dup - same
% str_count - NA pattern not supported, NA string treated as "NA"
% pattern spec like ignore.case(fixed("SPAM"))

% install.packages(repos=NULL, type="source",
%   "https://cran.r-project.org/src/contrib/Archive/stringr/stringr_0.6.2.tar.gz")
%
% library("stringr")
%
% unlist(packageDescription("stringr")[c("Version", "Date/Publication")])
% ##               Version      Date/Publication
% ##               "0.6.2" "2012-12-06 08:39:59"
%
% str_c(character(0), LETTERS[1:6])
% ## [1] "A" "B" "C" "D" "E" "F"
%
% str_c(c(NA, "a"), LETTERS[1:6])
% ## [1] "NAA" "aB"  "NAC" "aD"  "NAE" "aF"
%
% str_detect(c(NA, "a"), LETTERS[1:6])
% ## [1]    NA FALSE    NA FALSE    NA FALSE
%
% str_detect(character(0), LETTERS[1:6])
% ## Error in mapply(FUN = "grepl", SIMPLIFY = FALSE, USE.NAMES = FALSE, c("A",  :
% ##   zero-length inputs cannot be mixed with those of non-zero length
%
% str_dup(c(NA, "a"), 1:6)
% ## [1] "NA"         "aa"         "NANANA"     "aaaa"       "NANANANANA"
% ## [6] "aaaaaa"
%
% str_dup(character(0), 1:6)
% ## Error in data.frame(string, times) :
% ##   arguments imply differing number of rows: 0, 6
%
% str_locate_all(c("bacon spam spam", "spam", "eggs"), ignore.case(fixed("SPAM")))
% ## [[1]]
% ##      start end
% ##
% ## [[2]]
% ##      start end
% ##
% ## [[3]]
% ##      start end
% ##
% ## Warning message:
% ## In gregexpr("SPAM", c("bacon spam spam", "spam", "eggs"), fixed = TRUE,  :
% ##   argument 'ignore.case = TRUE' will be ignored
%
% str_locate(c("bacon spam spam", "spam", "eggs"), "spam")
% ##      start end
% ## [1,]     7  10
% ## [2,]     1   4
% ## [3,]    NA  NA
%
% str_locate_all(c("bacon spam spam", "spam", "eggs"), "spam")
% ## [[1]]
% ##      start end
% ## [1,]     7  10
% ## [2,]    12  15
% ##
% ## [[2]]
% ##      start end
% ## [1,]     1   4
% ##
% ## [[3]]
% ##      start end
%
% str_extract_all(c("bacon spam spam", "spam eggs", "eggs spam", "spam eggs"), c("spam", "eggs"))
% ## [[1]]
% ## [1] "spam" "spam"
% ##
% ## [[2]]
% ## [1] "eggs"
% ##
% ## [[3]]
% ## [1] "spam"
% ##
% ## [[4]]
% ## [1] "eggs"
%
% str_extract_all(c("bacon spam spam", "spam eggs", "eggs spam", "spam eggs"), c("spam", NA))
% ## Error in (function (pattern, text, ignore.case = FALSE, perl = FALSE,  :
% ##   invalid 'pattern' argument
%
% str_extract_all(c("bacon spam spam", "spam eggs", "eggs spam", NA), c("spam", "eggs"))
% ## [[1]]
% ## [1] "spam" "spam"
% ##
% ## [[2]]
% ## [1] "eggs"
% ##
% ## [[3]]
% ## [1] "spam"
% ##
% ## [[4]]
% ## character(0)
%
% str_count(c("bacon spam spam", "spam eggs", "eggs spam", NA), c("spam", "NA"))
% ## [1] 2 0 1 1
%
% str_count(c("bacon spam spam", "spam eggs", "eggs spam", NA), c("spam", NA))
% ## Error in (function (pattern, text, ignore.case = FALSE, perl = FALSE,  :
% ##   invalid 'pattern' argument





\subsection{Naming}

Function and argument names use a combination of lowercase letters
and underscores (and no dots). To avoid namespace clashes,
all function names feature the ``\texttt{stri\_}'' prefix.
Names are fairly self-explanatory, e.g.,
\texttt{stri\_locate\_first\_regex} and \texttt{stri\_locate\_all\_fixed}
find, respectively, the first match to a regular expression and
all occurrences of a substring as-is.

% There are also synonyms for certain operations,
% but actually maybe we should have them deprecated...
% \texttt{stri_locate_all_fixed(haystack, needle)}
% \texttt{stri_locate(haystack, fixed=needle, mode="all")}
% \texttt{stri_locate_all(haystack, fixed=needle)}




\subsection{Vectorisation}

Individual character (or code point) strings can be entered using
double quotes or apostrophes:

\begin{verbatim}<<>>=
"spam"  # or 'spam'
@\end{verbatim}

However, as the  {R} language does not feature any
classical scalar types, strings are wrapped around atomic vectors
of type ``\texttt{character}'':

\begin{verbatim}<<>>=
typeof("spam")  # object type; see also is.character() and is.vector()
length("spam")  # how many strings are in this vector?
@\end{verbatim}

\noindent
Hence, we will be using the terms ``string'' and ``character vector
of length 1'' interchangeably.

Not having a separate scalar type is very convenient; the so-called
\emph{vectorisation} strategy encourages writing code that
processes whole collections of objects, all at once,
regardless of their size.

For instance, given the following character vector:


\begin{verbatim}<<>>=
pythons <- c("Graham Chapman", "John Cleese", "Terry Gilliam",
  "Eric Idle", "Terry Jones", "Michael Palin")
@\end{verbatim}

\noindent
we can separate the first and the last names from
each other (assuming for simplicity that no middle names are given),
using just a single function call:

\begin{verbatim}<<>>=
(pythons <- stri_split_fixed(pythons, " ", simplify=TRUE))
@\end{verbatim}

\noindent
Due to {vectorisation}, we can generally
avoid using the \texttt{for}- and \texttt{while}-loops
(``for each string in a vector\dots''),
which makes the code much more readable, maintainable, and faster to execute.

% round(c(1, 3.141593, 2.71828), 2)




\subsection{Acting elementwise with recycling}


% in other context, recycling rule also allows use to
% operate on "every other, every 3rd, ...." element
% like in k-fold cross-validation,
% some Taylor series expansions, ...

Binary and higher-arity operations in {R}
are oftentimes vectorised with respect to all arguments
(or at least to the crucial, non-optional ones).
As a prototype, let us consider the binary arithmetic,
logical, or comparison operators
(and, to some extent, \texttt{paste()},
\texttt{strrep()}, and more generally \texttt{mapply()}),
for example the multiplication:



\begin{verbatim}<<>>=
c(10, -1) * c(1, 2, 3, 4)  # == c(10, -1, 10, -1) * c(1, 2, 3, 4)
@\end{verbatim}

\noindent
Calling ``\texttt{x * y}'' multiplies the corresponding components
of the two vectors elementwisely. As one operand happens to be shorter
than another, the former is recycled as many times as necessary
to match the length of the latter (there would be a warning if partial
recycling occurred). Also, acting on a zero-length
input always yields an empty vector.

%   exceptions: \texttt{collapse} is a single string in \texttt{stri_join}
% c(1, 2) + numeric(0)
% paste does not behave this way

All functions in \textit{stringi} follow this convention
(with some obvious exceptions, such as the \texttt{collapse}
argument in \texttt{stri\_join()}, \texttt{locale} in \texttt{stri\_datetime\_parse()}, etc.).
In particular, all string search functions are vectorised
with respect to both the  \texttt{haystack} and the \texttt{needle} arguments
(and, e.g., the replacement string, if applicable).

Some users, unaware of this rule, might find this behaviour
unintuitive at the beginning and thus miss out on how powerful it is. Therefore, let us enumerate
the most noteworthy scenarios that are possible thanks to the arguments' recycling,
using the call to \texttt{stri\_count\_fixed(haystack, needle)}
(which looks for a needle in a haystack)
as an illustration:

\begin{itemize}
\item many strings -- one pattern:

\begin{verbatim}<<>>=
stri_count_fixed(c("abcd", "abcabc", "abdc", "dab", NA), "abc")
@\end{verbatim}

(there is 1 occurrence of \texttt{"abc"} in \texttt{"abcd"},
2 in \texttt{"abcabc"}, and so forth);

\item one string -- many patterns:

\begin{verbatim}<<>>=
stri_count_fixed("abcdeabc", c("def", "bc", "abc", NA))
@\end{verbatim}

(\texttt{"def"} does not occur in \texttt{"abcdeabc"},
\texttt{"bc"} can be found therein twice, etc.);

\item each string -- its own corresponding pattern:

\begin{verbatim}<<>>=
stri_count_fixed(c("abca", "def", "ghi"), c("a", "z", "h"))
@\end{verbatim}

(there are two \texttt{"a"}s in \texttt{"abca"},
no \texttt{"z"} in \texttt{"def"}, and one \texttt{"h"} in \texttt{"ghi"});

\item each row in a matrix -- its own corresponding pattern:

\begin{verbatim}<<>>=
(haystack <- matrix(  # example input
  do.call(stri_join,
    expand.grid(
      c("a", "b", "c"), c("a", "b", "c"), c("a", "b", "c")
    )), nrow=3))
needle <- c("a", "b", "c")
matrix(stri_count_fixed(haystack, needle),  # call to stringi
  nrow=3, dimnames=list(needle, NULL))
@\end{verbatim}

(this looks for \texttt{"a"} in the 1st row of
\texttt{haystack}, \texttt{"b"} in the 2nd row, and \texttt{"c"} in the 3rd;
in particular, there are 3 \texttt{"a"}s in \texttt{"aaa"}, 2 in \texttt{"aba"},
and 1 \texttt{"b"} in \texttt{"baa"};
this is possible due to the fact that matrices are
represented as ``flat'' vectors of length \texttt{nrow*ncol},
whose elements are read in a column-major ({Fortran}) order;
therefore, here,
pattern \texttt{"a"} is being sought in the 1st, 4th, 7th,
\dots{} string in \texttt{haystack}, i.e., \texttt{"aaa"}, \texttt{"aba"}, \texttt{"aca"}, \dots;
pattern \texttt{"b"} in the 2nd, 5th, 8th, \dots{} string;
and \texttt{"c"} in the 3rd, 6th, 9th, \dots{} one);

\medskip
On a side note, to match different patterns
with respect to each column, we can (amongst others)
apply matrix transpose twice (\texttt{t(stri_count_fixed(t(haystack), needle))}).

% or use the \texttt{rep()} function to properly replicate the \textit{needles}:

% <<>>=
% (At <- t(haystack))  # example haystack
% needle <- rep(c("a", "b", "c"), each=nrow(At))
% matrix(stri_count_fixed(At, needle), ncol=3)
% @
%
% A similar search in the case of a data frame-type input
% (any list of character vectors of identical lengths)
% can be performed by means of a call to \texttt{mapply()}:
%
%
%
% <<>>=
% (At.df <- as.data.frame(At))
% mapply(stri_count_fixed, At.df, c("a", "b", "c"))
% @

\item all strings -- all patterns:

% TODO: better not use outer -- do not rep needle

\begin{verbatim}<<>>=
haystack <- c("aaa", "bbb", "ccc", "abc", "cba", "aab", "bab", "acc")
needle <- c("a", "b", "c")
structure(
  outer(haystack, needle, stri_count_fixed),
  dimnames=list(haystack, needle))  # add row and column names
@\end{verbatim}

(which computes the counts over the Cartesian product
of the two arguments);

% \ifnotJSSversion
Equivalently:

\begin{verbatim}<<>>=
matrix(
  stri_count_fixed(rep(haystack, each=length(needle)), needle),
  byrow=TRUE, ncol=length(needle), dimnames=list(haystack, needle))
@\end{verbatim}
% \fi

\end{itemize}


% NOTE:
% In `stri_subset*`
%   and their replacement versions, `pattern` and `value` cannot be longer
%   than `str` (but now they are recycled if necessary).




\subsection{Missing values}

Some base {R} string processing functions,
e.g., \texttt{paste()}, treat missing values as literal \texttt{"NA"}
strings.
\textit{stringi}, however, does enforce the consistent
propagation of missing values (like arithmetic operations):

\begin{verbatim}<<>>=
paste(c(NA_character_, "b", "c"), "x", 1:2)  # base R
stri_join(c(NA_character_, "b", "c"), "x", 1:2)  # stringi
@\end{verbatim}

For dealing with missing values, we may rely on the
convenience functions such as \texttt{stri\_omit\_na()} or
\texttt{stri\_replace\_na()}.
% and, if additionally we would like to remove empty strings in a vector,
% \texttt{stri\_omit\_empty\_na()}:
%
% #stri_replace_na(x, "<NA>") %s+% "!"
% stri_omit_empty_na(x) %s+% "!"



\subsection{Data flow}

All vector-like arguments (including factors and objects)
in \textit{stringi} are treated in the same manner:
for example, if a function expects a character vector on input
and an object of other type is provided,
\texttt{as.character()} is called first
(we see that in the example above,
``\texttt{1:2}'' is treated as \texttt{c("1", "2")}).






% The functions are, of course,  pipe operator-friendly:
%
% % <<>>=
% % y |> stri_sub_replace(24, length=5, replacement="spam") # bacon → spam
% % @
%
%
% <<>>=
% y <- "spam, spam, eggs, bacon, and tasty spam"
% y |> stri_locate_all(., fixed="spam") |> stri_sub_replace_all(y, ., replacement="ham")
% @



% order of inputs - "x" goes first

% When a character vector argument is expected, factors and other vectors
% coercible to characters vectors are silently converted with as.character,
% otherwise an error is generated. Coercion from a list of non-atomic
% vectors each of length 1 issues a warning.
%
% When a logical, numeric, or integer vector argument is expected,
% factors are converted with as.*(as.character(...)), and other
% coercible vectors are converted with as.*, otherwise an error is generated.
%
% Generally, all our functions drop input objects' attributes
% (e.g., names, dim, etc.). This is generally because of advanced
% vectorization and for efficiency reasons. Thus, if arguments'
% preserving is needed, please remember to copy important attributes
% manually or use, e.g., the subsetting operation like x[] <- stri_...(x, ...).


Following \citep{Wickham2010:stringr}, \textit{stringi}
makes sure the output data types are consistent
and that different functions are interoperable.
This makes operation chaining easier and less error prone.

For example, \texttt{stri\_extract\_first\_regex()}
finds the first occurrence of a pattern in each string,
therefore the output is a character of the same length
as the input (with recycling rule in place if necessary).



% character vectors or list of character vectors
%
% matrices or lists of matrices
%
% integer vectors or lists of integer vectors
%
% etc.





\begin{verbatim}<<>>=
haystack <- c("bacon", "spam", "jam, spam, bacon, and spam")
stri_extract_first_regex(haystack, "\\b\\w{1,4}\\b")
@\end{verbatim}

Note that a no-match (here, we have been looking for words
of at most 4 characters)
is marked with a missing string.
This makes the output vector size consistent with the length of
the inputs.

On the other hand, \texttt{stri\_extract\_all\_regex()}
identifies all occurrences of a pattern, whose counts may differ from input to input,
therefore it yields a list of character vectors.

\begin{verbatim}<<>>=
stri_extract_all_regex(haystack, "\\b\\w{1,4}\\b", omit_no_match=TRUE)
@\end{verbatim}

If the 3rd argument was not specified, a no-match
would be represented by a missing value (for consistency with the
previous function).


Also, care is taken so that the ``data'' or ``\texttt{x}''
argument is most often listed as the first one
(e.g., in base {R} we have \texttt{grepl(needle, haystack)}
vs \texttt{stri\_detect(haystack, needle)} here).
% \texttt{stri\_sprintf()} being one of exceptions to this rule, though).
This makes the functions more intuitive to use,
but also more forward pipe operator-friendly
(either when using ``\texttt{|>}'' introduced in {R} 4.1
or ``\texttt{\%>\%}'' from \textit{magrittr}).


Furthermore, for increased convenience, some functions have been added
despite the fact that they can be trivially reduced to a series of
other calls.
In particular, writing:

\begin{verbatim}<<results="hide">>=
stri_sub_all(haystack,
  stri_locate_all_regex(haystack, "\\b\\w{1,4}\\b", omit_no_match=TRUE))
@\end{verbatim}

\noindent
yields the same result as in the previous example,
but refers to \texttt{haystack} twice.


\subsection[Further deviations from base R]{Further deviations from base {R}}

\textit{stringi} can be used as a replacement of the existing string
processing functions. Also, it offers many
facilities not available in base {R}.
Except for being fully vectorised with respect to all crucial
arguments, propagating missing values and empty vectors consistently,
and following coherent naming conventions, our functions
deviate from their classic counterparts even further.




% <<>>=
% x <- matrix(LETTERS, nrow=2, dimnames=list(c("alpha", "beta"), NULL))
% x[] <- stri_trans_tolower(x)
% print(x)
% @


\paragraph{Following Unicode standards.}
Thanks to the comprehensive coverage of the most important
services provided by \textit{ICU}, its users gain access to
collation, pattern searching, normalisation, transliteration, etc.,
that follow the recent Unicode standards for text processing
in any locale.
Due to this, as we state in Section~\ref{Sec:encoding},
all inputs are converted to Unicode and outputs are always
in UTF-8.



\paragraph{Portability issues in base {R}.}
As we have mentioned in the introduction,
base {R} string operations have traditionally been
limited in scope. There also might be some issues with regards to their portability,
reasons for which may be plentiful.
For instance, varied versions of the
\textit{PCRE} (8.x or 10.x)
pattern matching libraries may be linked to
during the compilation of {R}. On Windows, there is a custom implementation
of \textit{iconv} that has a set of character encoding
IDs not fully compatible with that on GNU/Linux: to select
the Polish locale, we are required to pass \texttt{"Polish\_Poland"}
to \texttt{Sys.setlocale()} on Windows whereas \texttt{"pl\_PL"} on
Linux.
Interestingly, {R} can be built against the system \textit{ICU}
so that it uses its Collator for comparing strings (e.g., using the ``\texttt{<=}''
operator), however this is only optional and does not provide access to any
other Unicode services.


%
% A call to \texttt{extSoftVersion()} reports on the versions of
% third-party software  used by {R}.
% some resources might not be unavailable/not installed
% resources (e.g., locales) may be fetched by means of different IDs
% not necessarily the fastest
% %                      PCRE                       ICU                       TRE                     iconv
% %        "10.34 2019-11-21"                    "66.1" "TRE 0.8.0 R_fixes (BSD)"              "glibc 2.31"
% %
% %        PCRE                       ICU     TRE                        iconv
% % "8.42 2018-03-20"          "55.1"  "TRE 0.8.0 R_fixes (BSD)"  "win_iconv"









% <<>>=
% oldlocale <- Sys.getlocale("LC_COLLATE")
% Sys.setlocale("LC_COLLATE", "sk_SK")
% sort(c("hladný", "chladný"))
% Sys.setlocale("LC_COLLATE", oldlocale)
% @
%
%
% % Warning message:
% % In Sys.setlocale("LC_COLLATE", "sk_SK") :
% %   OS reports request to set locale to "sk_SK" cannot be honored
% %
%
%
% This code works on my Linux, but is not portable. It's because:
%
%     Other Linux users may not have Slovak rule-base installed (and not everyone has abilities to do it on his/her own).
%     Windows users don't use BCP 47-based locale names. There, LCID \texttt{Slovak_Slovakia.1250} is appropriate.
%
% And so on.





% x <- "AEZaezĄĘŻąęż"
% stri_sub(x, gregexpr("[[:alpha:]]", x, perl=FALSE)[[1]], length=1)
% #stri_sub(x, gregexpr("\\p{L}", x, perl=FALSE)[[1]], length=1)
% stri_sub(x, gregexpr("[[:alpha:]]", x, perl=TRUE)[[1]], length=1)
% stri_sub(x, gregexpr("\\p{L}", x, perl=TRUE)[[1]], length=1)
% stri_extract_all_regex(x, "[[:alpha:]]")[[1]]
% stri_extract_all_regex(x, "\\p{L}")[[1]]
%
%
% Linux (UTF-8 locale):
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
% [1] "A" "E" "Z" "a" "e" "z"
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"

% Windows (UTF-8)
%
%  stri_sub(x, gregexpr("[[:alpha:]]", x, perl=FALSE)[[1]], length=1)
% [1] "A" "E" "Z" "a" "e" "z"
% > #stri_sub(x, gregexpr("\\p{L}", x, perl=FALSE)[[1]], length=1)
% > stri_sub(x, gregexpr("[[:alpha:]]", x, perl=TRUE)[[1]], length=1)
% [1] "A" "E" "Z" "a" "e" "z"
% > stri_sub(x, gregexpr("\\p{L}", x, perl=TRUE)[[1]], length=1)
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
% > stri_extract_all_regex(x, "[[:alpha:]]")[[1]]
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
% > stri_extract_all_regex(x, "\\p{L}")[[1]]
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"

%
% > stri_sub(x, gregexpr("[[:alpha:]]", x, perl=FALSE)[[1]], length=1)
% [1] "A" "E" "Z" "a" "e" "z" "Ę" "ę"
% > #stri_sub(x, gregexpr("\\p{L}", x, perl=FALSE)[[1]], length=1)
% > stri_sub(x, gregexpr("[[:alpha:]]", x, perl=TRUE)[[1]], length=1)
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
% > stri_sub(x, gregexpr("\\p{L}", x, perl=TRUE)[[1]], length=1)
% [1] "A" "E" "Z" "a" "e" "z" "Ę" "ę"
% > stri_extract_all_regex(x, "[[:alpha:]]")[[1]]
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
% > stri_extract_all_regex(x, "\\p{L}")[[1]]
%  [1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"

% FUTURE: Universal C Runtime UCRT Windows
% https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/index.html




For example, let us consider the matching
of ``all letters'' by means of the built-in \texttt{gregexpr()} function
and the \textit{TRE} (\texttt{perl=FALSE})
and \textit{PCRE} (\texttt{perl=TRUE}) libraries
using a POSIX-like and Unicode-style character set
(see Section~\ref{Sec:regex} for more details):

\begin{Schunk}
\begin{Sinput}
R> x <- "AEZaezĄĘŻąęż"  # "AEZaez\u0104\u0118\u017b\u0105\u0119\u017c"
R> stri_sub(x, gregexpr("[[:alpha:]]", x, perl=FALSE)[[1]], length=1)
R> stri_sub(x, gregexpr("[[:alpha:]]", x, perl=TRUE)[[1]],  length=1)
R> stri_sub(x, gregexpr("\\p{L}", x, perl=TRUE)[[1]],       length=1)
\end{Sinput}
\end{Schunk}

On Ubuntu Linux 20.04 (UTF-8 locale), the respective outputs are:

\begin{Schunk}
\begin{Soutput}
[1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
[1] "A" "E" "Z" "a" "e" "z"
[1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
\end{Soutput}
\end{Schunk}

On Windows, when \texttt{x} is marked as UTF-8
(see Section \ref{Sec:encoding}), the author obtained:

\begin{Schunk}
\begin{Soutput}
[1] "A" "E" "Z" "a" "e" "z"
[1] "A" "E" "Z" "a" "e" "z"
[1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
\end{Soutput}
\end{Schunk}

And again on Windows using the Polish locale
but \texttt{x} marked as natively-encoded (CP-1250 in this case):

\begin{Schunk}
\begin{Soutput}
[1] "A" "E" "Z" "a" "e" "z" "Ę" "ę"
[1] "A" "E" "Z" "a" "e" "z" "Ą" "Ę" "Ż" "ą" "ę" "ż"
[1] "A" "E" "Z" "a" "e" "z" "Ę" "ę"
\end{Soutput}
\end{Schunk}

As we mention in Section~\ref{Sec:collator},
when \textit{stringi} links to \textit{ICU} built from sources
(\texttt{install.pa\-ckages("stringi", configure.args="--disable-pkg-config")}),
we are always guaranteed to get the same results on every platform.




\paragraph{High performance of \textit{stringi}.}
Because of the aforementioned reasons, functions in \textit{stringi}
do not refer to their  base {R} counterparts.
The operations that do not rely on \textit{ICU} services
have been rewritten from scratch with speed and portability in mind.
For example, here are some timings of string concatenation:


\begin{verbatim}<<performance1,cache=TRUE>>=
x <- stri_rand_strings(length(LETTERS) * 1000, 1000)
microbenchmark::microbenchmark(
  join2=stri_join(LETTERS, x, sep="", collapse=", "),
  join3=stri_join(x, LETTERS, x, sep="", collapse=", "),
  r_paste2=paste(LETTERS, x, sep="", collapse=", "),
  r_paste3=paste(x, LETTERS, x, sep="", collapse=", ")
)
@\end{verbatim}

Another example -- timings of fixed pattern searching:

\begin{verbatim}<<performance2,echo=-1,cache=TRUE>>=
set.seed(123)
x <- stri_rand_strings(100, 100000, "[actg]")
y <- "acca"
microbenchmark::microbenchmark(
  fixed=stri_locate_all_fixed(x, y),
  regex=stri_locate_all_regex(x, y),
  coll=stri_locate_all_coll(x, y),
  r_tre=gregexpr(y, x),
  r_pcre=gregexpr(y, x, perl=TRUE),
  r_fixed=gregexpr(y, x, fixed=TRUE)
)
@\end{verbatim}


\paragraph{Different default argument and greater configurability.}
Some functions in \textit{stringi} have different,
more natural default arguments,
e.g., \texttt{paste()} has \texttt{sep=" "} but
\texttt{stri\_join()} has \texttt{sep=""}.
Also, as there is no one-fits-all solution to all problems,
many arguments have been introduced for more detailed tuning.

\paragraph{Preserving attributes.}
Generally, \textit{stringi} preserves no object attributes
whatsoever, but a user can make sure themself
that this is becomes the case, e.g., by calling
``\texttt{x[] <- stri\_...(x, ...)}''
or ``\texttt{`attributes<-`(stri\_...(x, ...), attributes(x))}''.





% \paragraph{A note on the \textit{stringx} package.}
% The \textit{stringx} package \citep{stringx} offers Unicode-aware
% drop-in replacements for base {R} string processing functions.
% It is implemented using \textit{stringi},
% hence many concepts described herein shall apply to the said package
% as well.




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Basic string operations}\label{Sec:basic}

Let us proceed with a detailed description of the most important
facilities in the \textit{stringi} package that might be of interest to
the broad statistical and data analysis audience.



\subsection{Computing length and width}


First we shall review the functions related to determining
the number of entities in each string.



% \paragraph{Length.}
Let us consider the following character vector:

\begin{verbatim}<<>>=
x <- c("spam", "你好", "\u200b\u200b\u200b", NA_character_, "")
@\end{verbatim}

The \texttt{x} object consists of 5 character strings:

\begin{verbatim}<<>>=
length(x)
@\end{verbatim}


\texttt{stri\_length()} computes the length of each string.
More precisely, the function gives the number of Unicode code points
in each string, see Section~\ref{Sec:codepoints} for more details.

\begin{verbatim}<<>>=
stri_length(x)
@\end{verbatim}

\noindent
% \texttt{stri\_length(x)} returns a numeric vector \texttt{s},
% with the same number of elements as \texttt{x}, such that, for every \texttt{i},
% \texttt{s[i]} is the length of the string \texttt{x[i]}.
The first string carries 4 ASCII (English) letters,
the second consists of 2 Chinese characters (U+4F60, U+597D; a greeting),
and the third one is comprised of 3 zero-width spaces (U+200B).
Note that the 5th element in \texttt{x} is an empty string, \texttt{""},
hence its length is  0.
Moreover, there is a missing (\texttt{NA}) value
at index 4, therefore the corresponding length is undefined as well.
% \textit{stringi} applies this rule consistently across all its functions.




% \paragraph{Width.}
When formatting strings for display
(e.g., in a report dynamically generated with \texttt{Sweave()}
or \textit{knitr}; see \citealp{knitr}),
a string's width estimate may be more informative --
an approximate number of text columns it will occupy when printed
using a monospaced font.
In particular, many Chinese, Japanese, Korean, and most emoji
characters take up two text cells. Some code points, on the other hand,
might be of width 0 (e.g., the above ZERO WIDTH SPACE, U+200B).



% \begin{CJK*}{UTF8}{bsmi}
\begin{verbatim}<<>>=
stri_width(x)
@\end{verbatim}
% \end{CJK*}

\noindent



% SKIP: stri_numbytes

% SKIP: stri_isempty

%\paragraph{Zero-length.}
%To quickly determine which of the items are empty strings, we may call:
%
%<<>>=
%stri_isempty(x)
%@
%
%\noindent
%Note that we distinguish between an empty character vector
%(\texttt{character(0)}, i.e., a zero-length sequence)
%and an empty string, i.e., a string of length 0 wrapped in a vector
%of length~1.
%
%<<>>=
%length(character(0))      # no strings at all
%stri_length(character(0))
%length("")                # one empty string
%stri_length("")
%@









\subsection{Joining}

Below we describe the functions that are related to string concatenation.


\paragraph{Operator \texttt{\%s+\%}.}
To join  the corresponding strings in two character vectors,
we may use the binary \texttt{\%s+\%} operator:

\begin{verbatim}<<>>=
x <- c("tasty", "delicious", "yummy", NA)
x %s+% " " %s+% c("spam", "bacon")
@\end{verbatim}

% character(0) %s+% c("spam", "bacon")

% This operator is vectorised in exactly the same manner
% as other arithmetic operators in {R}.
% In particular, the recycling rule is used if the inputs are of different
% lengths. If one of the arguments is empty, the result is a zero-length
% vector as well. Moreover, \textit{stringi} \textit{does} enforce the consistent
% propagation of missing values
% (unlike the built-in \texttt{paste()} function):
%
% <<>>=
% x <- c("spam", "bacon", "", "sausage", NA, "spam")
% x %s+% "!"
% @




\paragraph{Flattening.}
The elements in a character vector can be joined (``aggregated'')
to form a single string via a call to  \texttt{stri\_flatten()}:

\begin{verbatim}<<>>=
stri_flatten(stri_omit_na(x), collapse=", ")
@\end{verbatim}

\noindent
Note that the token separator, given by the \texttt{collapse} argument,
defaults to the empty string.



\paragraph{Generalisation.}
Both the \texttt{\%s+\%} operator and the \texttt{stri\_flatten()} function
are generalised by
\texttt{stri\_join()} (alias: \texttt{stri\_paste()}, \texttt{stri\_c()}):

\begin{verbatim}<<>>=
stri_join(c("X", "Y", "Z"), 1:6, "a")  # sep="", collapse=NULL
@\end{verbatim}

By default, the \texttt{sep} argument, which controls how corresponding
strings are delimited, is set to the empty string
(like in the base \texttt{paste0()} but unlike in \texttt{paste()}).
Moreover, \texttt{collapse} is \texttt{NULL}, which means that
the resulting outputs will not be joined to form a single string.
This can be changed if need be:

\begin{verbatim}<<>>=
stri_join(c("X", "Y", "Z"), 1:6, "a", sep="_", collapse=", ")
@\end{verbatim}



\noindent
Note how the two (1st, 3rd) shorter vectors were {recycled} to match
the longest (2nd) vector's length. The latter was of numeric type,
but it was implicitly coerced via a call to \texttt{as.character()}.


% paste()  sep="" by default
% paste0() sep=" "
% NA handling, character(0), UTF-8 output as usual in stringi


% \ifnotJSSversion
More examples:

\begin{verbatim}<<>>=
stri_join(pythons[, 2], pythons[, 1], sep=", ")
outer(LETTERS[1:3], 1:5, stri_join, sep=".")  # outer product
@\end{verbatim}
% \fi



\paragraph{Duplicating.}
To duplicate given strings, we call
\texttt{stri\_dup()} or the \texttt{\%s*\%} operator:


\begin{verbatim}<<>>=
stri_dup(letters[1:5], 1:5)
@\end{verbatim}

The above is synonymous with \texttt{letters[1:5] \%s*\% 1:5}.


\paragraph{Within-list joining.}
There is also a convenience function that applies \texttt{stri\_flatten()}
on each character vector in a given list:

\begin{verbatim}<<>>=
words <- list(c("spam", "bacon", "sausage", "spam"), c("eggs", "spam"))
stri_join_list(words, sep=", ")  # collapse=NULL
@\end{verbatim}

% \ifnotJSSversion
\begin{verbatim}<<>>=
stri_join_list(words, sep=", ", collapse=";\n")
@\end{verbatim}
% \fi

\noindent
This way, a list of character vectors can be converted to
a character vector. Such sequences of variable length sequences of
strings are generated by, amongst others,
\texttt{stri\_sub\_all()} and \texttt{stri\_extract\_all()}.






\subsection{Extracting and replacing substrings}

Next group of functions deals with the extraction and replacement
of particular sequences of code points in given strings.

\paragraph{Indexing vectors.}
Recall that in order to select a subsequence from any {R} vector,
we use the square-bracket operator\footnote{More precisely, \texttt{x[i]}
is a syntactic sugar for a call to \texttt{`[`(x, i)}.
Moreover, if \texttt{x} is a list, \texttt{x[[i]]} can be used to
extract its \texttt{i}-th element (alias \texttt{`[[`(x, i)}).
Knowing the ``functional'' form of the operators allows us to, for instance,
extract all first elements from each vector in a list
by simply calling \texttt{sapply(x, "[[", 1)}.}
with an index vector consisting of either
non-negative integers, negative integers,
or logical values\footnote{If an object's \texttt{names} attribute is set,
indexing with a character vector is also possible.}.

For example, here is how to select specific elements in a vector:

\begin{verbatim}<<>>=
x <- c("spam", "buckwheat", "", NA, "bacon")
x[1:3]                           # from 1st to 3rd string
x[c(1, length(x))]               # 1st and last
@\end{verbatim}

\noindent
Exclusion of elements at specific positions can be performed like:

\begin{verbatim}<<>>=
x[-1]                            # all but 1st
@\end{verbatim}

\noindent
Filtering based on a logical vector can be used to extract
strings fulfilling desired criteria:

\begin{verbatim}<<>>=
x[!stri_isempty(x) & !is.na(x)]
@\end{verbatim}


\paragraph{Extracting substrings.}
A character vector is, in its very own essence, a sequence of
sequences of code points.
To extract specific substrings from each string in a collection,
we can use the \texttt{stri\_sub()} function.

\begin{verbatim}<<>>=
y <- "spam, egg, spam, spam, bacon, and spam"
stri_sub(y, 18)             # from 18th code point to end
stri_sub(y, 12, to=15)      # from 12th to 15th code point (inclusive)
@\end{verbatim}

Negative indices count from the end of a string.

\begin{verbatim}<<>>=
stri_sub(y, -15, length=5)  # 5 code points from 15th last
@\end{verbatim}




\paragraph{\texttt{stri\_sub\_all()} function.}
% \ifnotJSSversion
% The \texttt{stri\_sub()}  function is of course vectorised with respect
% to all its arguments
% (the subsetted character vector, \texttt{from}, and \texttt{to} or \texttt{length}).
% If one of the vectors is of smaller length than the other ones,
% the recycling rule is applied as usual. For instance:
%
% <<>>=
% stri_sub(y, c(1, 12, 18), length=4) # different substrings of one string
% stri_sub(x[c(1, 2, 4)], from=-3)    # same substrings of different strings
% stri_sub(x[c(1, 2, 4)],
%   c(-4, -2, -5))  # different substrings of different strings
% @
% \fi
If some deeper vectorisation level is necessary, \texttt{stri\_sub\_all()}
comes in handy. It extracts multiple (possibly different) substrings
from all the strings provided:


\begin{verbatim}<<>>=
(z <- stri_sub_all(
              c("spam",     "bacon", "sorghum"),
  from   = list(c(1, 3, 4), -3,      c(2, 4)),
  length = list(1,           3,      c(4, 3))))
@\end{verbatim}

As the number of substrings to extract from each string might vary,
the result is a list of character strings.
We have obtained:
substrings of length 1 starting at positions 1, 3, and 4 in \texttt{x[1]},
then a length-3 substring that starts at the 3rd code point
from the end of \texttt{x[2]},
and length-4 and -3 substrings starting at, respectively,
the 2nd and 4th code point
of \texttt{x[3]} (where \texttt{x} denotes the subsetted vector).


% \ifnotJSSversion
Recall that the strings may all be concatenated by means of the
aforementioned \texttt{stri\_join\_list()} function.

\begin{verbatim}<<>>=
stri_join_list(z, sep=", ")
@\end{verbatim}



There is also a more flexible version
of the built-in \texttt{simplify2array()} function whose
aim is to convert such lists to matrices.

\begin{verbatim}<<>>=
stri_list2matrix(z, by_row=TRUE, fill="", n_min=5)
@\end{verbatim}
% \fi


% Here is a way to extract
% non-consecutive substrings from each string --
% ones that consist of the first and the last letter:
%
% <<>>=
% stri_join_list(stri_sub_all(x[c(1, 2, 4)], c(1, -1), length=1))
% @






\paragraph{``From--to'' and ``from--length'' matrices.}
The second parameter of both \texttt{stri\_sub()} and \texttt{stri\_sub\_list()}
can also be fed with a two-column matrix
of the form \texttt{cbind(from, to)}. Here, the first column
gives the start indices and the second column defines the end ones.
Such matrices are generated, amongst others, by the \texttt{stri\_locate\_*()}
functions (see below for details).

% \ifnotJSSversion
\begin{verbatim}<<>>=
(from_to <- cbind(from=c(1, 12, 18), to=c(4, 15, 21))) # +optional labels
stri_sub(y, from_to)
@\end{verbatim}


\noindent Another example (the recycling rule):
% \fi

\begin{verbatim}<<>>=
(from_to <- matrix(1:8, ncol=2, byrow=TRUE))
stri_sub(c("abcdefgh", "ijklmnop"), from_to)
@\end{verbatim}

\noindent
Due to recycling, this has extracted
elements at positions 1:2 from the 1st string,
at 3:4 from the 2nd one, 5:6 from the 1st, and 7:8 from the 2nd again.

Note the difference between the above output and the following one:

\begin{verbatim}<<>>=
stri_sub_all(c("abcdefgh", "ijklmnop"), from_to)
@\end{verbatim}

This time, we extract four identical sections from each of the two inputs.


\medskip
Moreover, if the second column of the index matrix is named
\texttt{"length"} (and only if this is exactly the case),
i.e., the indexer is of the form \texttt{cbind(from, length=length)},
extraction will be based on the extracted chunk size.




% \ifnotJSSversion
\paragraph{Permuting code points.}
Somewhat related to the above are different ways to construct
various permutations (possibly with replacement) of code points in a string:

\begin{verbatim}<<echo=-1>>=
set.seed(123)
stri_join_list(stri_sub_all("spam", c(4, 3, 2, 3, 1), length=1))
stri_rand_shuffle("bacon")  # random order
stri_reverse("spam")        # reverse order
@\end{verbatim}
% \fi

\paragraph{Replacing substrings.}
\texttt{stri\_sub\_replace()} returns a version
of a character vector with some chunks replaced by other
strings:

\begin{verbatim}<<>>=
stri_sub_replace(c("abcde", "ABCDE"),
  from=c(2, 4), length=c(1, 2), replacement=c("X", "uvw"))
@\end{verbatim}

\noindent
The above replaced ``\texttt{b}'' (the length-1 substring
starting at index 2 of the 1st string) with ``\texttt{X}''
and ``\texttt{DE}''
(the length-2 substring at index 4 of the 2nd string)
with ``\texttt{uvw}''.


Similarly, \texttt{stri\_sub\_replace\_all()} replaces
multiple substrings within each string in a character vector:

\begin{verbatim}<<>>=
stri_sub_replace_all(
                   c("abcde",  "ABCDE"),
  from        = list(c(2, 4),  c(0,    3,   6)),
  length      = list(  1,      c(0,    2,   0)),
  replacement = list(  "Z",    c("uu", "v", "wwww")))
@\end{verbatim}

\noindent
Note how we have obtained the insertion of new content
at the start and the end of the 2nd input.


\paragraph{Replacing substrings in-place.}
The corresponding {replacement functions} modify
a character vector in-place:

\begin{verbatim}<<>>=
y <- "spam, egg, spam, spam, bacon, and spam"
stri_sub(y, 7, length=3) <- "spam"  # in-place replacement, egg → spam
print(y)                            # y has changed
@\end{verbatim}

Note that the state of \texttt{y} has changed in such a way that the
substring of length 3 starting at the 7th code point
was replaced by a length-4 content.

Many replacements within a single string are also possible:

\begin{verbatim}<<>>=
y <- "aa bb cc"
stri_sub_all(y, c(1, 4, 7), length=2) <- c("A", "BB", "CCC")
print(y)                            # y has changed
@\end{verbatim}

\noindent
This has replaced 3 length-2 chunks within \texttt{y} with new content.


% \clearpage


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\section{Code-pointwise comparing}\label{Sec:fixed}

There are many circumstances where we are faced with testing
whether two strings (or parts thereof)
consist  of exactly the same Unicode code points, in exactly the same order.
These include, for instance, matching a nucleotide sequence
in a DNA profile and querying for system resources based on file names or UUIDs.
Such tasks, due to their simplicity, can be performed very efficiently.


\subsection{Testing for equality of strings}


% equivalence relation on the set of characters

To quickly test whether the corresponding strings in two character vectors
are identical (in a code-pointwise manner), we can use the \texttt{\%s===\%}
operator or, equivalently, the \texttt{stri\_cmp\_eq()} function.
Moreover, \texttt{\%s!==\%} and \texttt{stri\_cmp\_neq()}
implement the not-equal-to relation.

\begin{verbatim}<<>>=
"actg" %s===% c("ACTG", "actg", "act", "actga", NA)
@\end{verbatim}

Due to recycling, the first string was compared against the
5 strings in the 2nd operand. There is only 1 exact match.



\begin{table}[b!]
\centering
\begin{tabularx}{1.0\linewidth}{p{4.8cm}X}
\toprule
\bfseries Name(s) & \bfseries Meaning \\
\midrule
\texttt{stri\_count()} &  count pattern matches    \\
\midrule
\texttt{stri\_detect()} & detect pattern matches     \\
\midrule
\texttt{stri\_endswith()} &  [all but \texttt{regex}] detect pattern matches at end of string  \\
\midrule
\texttt{stri\_extract\_all()}, \texttt{stri\_extract\_first()}, \texttt{stri\_extract\_last()}  & extract pattern matches     \\
\midrule
\texttt{stri\_locate\_all()}, \texttt{stri\_locate\_first()}, \texttt{stri\_locate\_last()}  & locate pattern matches     \\
\midrule
\texttt{stri\_match\_all()}, \texttt{stri\_match\_first()}, \texttt{stri\_match\_last()}   &  [\texttt{regex} only] extract matches to regex capture groups   \\
\midrule
\texttt{stri\_replace\_all()}, \texttt{stri\_replace\_first()}, \texttt{stri\_replace\_last()}  &     substitute pattern matches with some replacement strings \\
\midrule
\texttt{stri\_split()}  & split up a string at pattern matches     \\
\midrule
\texttt{stri\_startswith()}  &  [all but \texttt{regex}] detect pattern matches at start of string   \\
\midrule
\texttt{stri\_subset()}, \texttt{`stri\_subset<-`()}  & return or replace strings
that contain pattern matches \\
\bottomrule
\end{tabularx}

\caption{\label{Tab:searchfuns} String search/pattern matching functions in \textit{stringi}.
Each function, unless otherwise indicated, can be used in conjunction
with any search engine, e.g., we have
\texttt{stri\_count\_fixed()} (see Section~\ref{Sec:fixed}),
\texttt{stri\_detect\_regex()} (see Section~\ref{Sec:regex}), and
\texttt{stri\_split\_coll()} (see Section~\ref{Sec:collator}).}
\end{table}


\subsection{Searching for fixed strings}


For detecting if a string contains
a given fixed substring  (code-pointwisely),
the fast KMP \citep{KnuthETAL1977:kmp} algorithm, with worst time complexity of $O(n+p)$
(where $n$ is the length of the string and $p$ is the length of the pattern),
has been implemented in \textit{stringi} (with numerous tweaks
for even faster matching).

Table~\ref{Tab:searchfuns} lists the string search functions available
in \textit{stringi}.  Below we explain their behaviour in the context of fixed
 pattern matching. Notably, their description
is quite detailed, because -- as we shall soon find out --
the corresponding operations are available for the two other search
engines: based on regular expressions and the \textit{ICU} Collator,
see Section~\ref{Sec:regex} and Section~\ref{Sec:collator}.
% It is also worth emphasising that, initially, the most basic string search API
% has been designed so as to be compatible with the early versions
% of the \textit{stringr} package (compare Table~\ref{Tab:oldstringr}).
% In the course of \textit{stringi}'s development, many new operations and extensions
% have been introduced.






\subsection{Counting matches}

The \texttt{stri\_count\_fixed()} function counts the number of
times a fixed pattern occurs in a given string.

\begin{verbatim}<<>>=
stri_count_fixed("abcabcdefabcabcabdc", "abc")  # search pattern is "abc"
@\end{verbatim}

% \ifnotJSSversion
Equivalently, we can call the more generic (see below)
function \texttt{stri\_count()} with  the \texttt{fixed=pattern} argument:

\begin{verbatim}<<>>=
stri_count("abcabcdefabcabcabdc", fixed="abc")
@\end{verbatim}
% \fi


% \ifnotJSSversion
Note that, unlike in the base {R} \texttt{grep()} function
(and the like), the pattern (``needle'') is given by the second argument
(here: ``\texttt{abc}''). This makes our function more
pipe-operator-friendly, because ``haystack'' can be forwarded as follows:

\begin{verbatim}<<>>=
c("abcabcdefabcabcabdc", "cba", NA) |> stri_count_fixed("abc")
@\end{verbatim}
% \fi



\subsection{Search engine options}

The pattern matching engine may be tuned up by passing
further arguments to the search functions (via ``\texttt{...}'';
they are redirected as-is to \texttt{stri\_opts\_fixed()}).
Table~\ref{Tab:fixed_opts} gives the list of available options.





First, we may switch on the simplistic\footnote{Which is not suitable
for real-world NLP tasks, as it assumes
that changing the case of a single code point always produces one and only
one item;
This way, \texttt{"groß"} does not compare equal to \texttt{"GROSS"},
see Section~\ref{Sec:collator} (and partially Section~\ref{Sec:regex}) for a workaround.}
case-insensitive matching.


\begin{verbatim}<<>>=
stri_count_fixed("ACTGACGacgggACg", "acg", case_insensitive=TRUE)
@\end{verbatim}

Second, we can indicate our interest in detecting
overlapping pattern matches or whether searching should continue
at the end of each match
(the latter being the default behaviour):

\begin{verbatim}<<>>=
stri_count_fixed("acatgacaca", "aca")  # overlap=FALSE (default)
stri_count_fixed("acatgacaca", "aca", overlap=TRUE)
@\end{verbatim}



\begin{table}[t!]
\centering

\begin{tabularx}{1.0\linewidth}{p{4cm}X}
\toprule
\bfseries{Option}            &\bfseries Purpose \\
\midrule
\texttt{case\_insensitive} & logical; whether to enable the simple
case-insensitive matching (defaults to \texttt{FALSE}) \\
\midrule
\texttt{overlap} & logical; whether to enable the detection of overlapping
matches (defaults to \texttt{FALSE});
available in \texttt{stri\_extract\_all\_fixed()},
\texttt{stri\_locate\_all\_fixed()}, and \texttt{stri\_count\_fixed()}
\\
\bottomrule
\end{tabularx}

\caption{\label{Tab:fixed_opts} Options for the fixed pattern search
engine, see \texttt{stri\_opts\_fixed()}.}
\end{table}



\subsection{Detecting and subsetting patterns}

A somewhat simplified version of the above search task involves asking
whether a pattern occurs in a string at all. Such an operation can be
performed with a call to \texttt{stri\_detect\_fixed()}.

\begin{verbatim}<<>>=
x <- c("abc", "abcd", "def", "xyzabc", "uabdc", "dab", NA, "abc")
stri_detect_fixed(x, "abc")
@\end{verbatim}

We can also indicate that a no-match is rather of our  interest
by passing \texttt{negate=TRUE}.
What is more, there is an option to stop searching
once a given number of matches has been found
in the \texttt{haystack} vector (as a whole),
which can speed up the processing of larger data sets:

\begin{verbatim}<<>>=
stri_detect_fixed(x, "abc", negate=TRUE, max_count=2)
@\end{verbatim}

\noindent
This can be useful in scenarios such as ``find the first 2 matching
resource IDs''.


\medskip
There are also functions that verify whether a string
starts or ends\footnote{Note that testing for a pattern match at the start
or end of a string has not been implemented separately for \texttt{regex} patterns,
which support \texttt{"\textasciicircum"} and \texttt{"\$"} anchors that  serve exactly this very purpose.}
with a pattern match:

\begin{verbatim}<<>>=
stri_startswith_fixed(x, "abc")  # from=1 - match at start
stri_endswith_fixed(x, "abc")    # to=-1 - match at end
@\end{verbatim}


\medskip
Pattern detection is often performed in conjunction
with character vector subsetting.
This is why we have a specialised (and hence slightly faster)
function that  returns only the strings that match a given pattern.


\begin{verbatim}<<>>=
stri_subset_fixed(x, "abc", omit_na=TRUE)
@\end{verbatim}

The above is equivalent to \texttt{x[which(stri\_detect\_fixed(x, "abc"))]}
(note the argument responsible for the removal of missing values),
but avoids writing \texttt{x} twice.
% The users of the pipe operator might find it particularly convenient:
It hence is particularly convenient when \texttt{x} is generated
programmatically on the fly, using some complicated expression.
Also, it works well with the forward pipe operator, as we can write
``\texttt{x |> stri\_subset\_fixed("abc", omit\_na=TRUE)}''.


% stri_subset_fixed(x, "abc", negate=TRUE)  # everything but the matches


There is also a replacement version of this function:

\begin{verbatim}<<>>=
stri_subset_fixed(x, "abc") <- c("*****", "***")  # modifies x in-place
print(x)  # x has changed
@\end{verbatim}


% In `stri_subset*`
%   and their replacement versions, `pattern` and `value` cannot be longer
%   than `str` (but now they are recycled if necessary).




\subsection{Locating and extracting patterns}

The functions from the \texttt{stri\_locate()} family
aim to pinpoint the positions of pattern matches.
First, we may be interested in getting to know the location of the
first or the last pattern occurrence:

\begin{verbatim}<<>>=
x <- c("aga", "actg", NA, "AGagaGAgaga")
stri_locate_first_fixed(x, "aga")
stri_locate_last_fixed(x, "aga", get_length=TRUE)
@\end{verbatim}

\noindent
In both examples we obtain a two-column matrix
with the number of rows determined by the recycling rule (here:
the length of \texttt{x}).
In the former case, we get a ``from--to'' matrix (\texttt{get\_length=FALSE};
the default) where missing values correspond to either missing inputs or
no-matches. The latter gives a ``from--length''-type matrix,
where negative lengths correspond to the not-founds.

Second, we may be yearning for the locations of all the matching
substrings. As the number of possible answers may vary from string to string,
the result is a list of index matrices.

\begin{verbatim}<<>>=
stri_locate_all_fixed(x, "aga", overlap=TRUE, case_insensitive=TRUE)
@\end{verbatim}

\noindent
Note again that a no-match is indicated by a single-row matrix
with two missing values (or with negative length if \texttt{get\_length=TRUE}).
% stringr v0.6.2 returned empty matrices
This behaviour can be changed by setting the \texttt{omit\_no\_match}
argument to \texttt{TRUE}.


\medskip
Let us recall that ``from--to'' and ``from--length''
matrices of the above kind constitute particularly
fine inputs to \texttt{stri\_sub()} and \texttt{stri\_sub\_all()}.
However, if merely the extraction of the matching substrings is needed,
it will be more convenient to rely on the functions from the
\texttt{stri\_extract()} family:

\begin{verbatim}<<>>=
stri_extract_first_fixed(x, "aga", case_insensitive=TRUE)
stri_extract_all_fixed(x, "aga",
  overlap=TRUE, case_insensitive=TRUE, omit_no_match=TRUE)
@\end{verbatim}

% <<>>=
% (res <- stri_extract_first_fixed(x, "aga", case_insensitive=TRUE))
% identical(res, stri_sub(x,
%   stri_locate_first_fixed(x, "aga", case_insensitive=TRUE)))
% (res <- stri_extract_all_fixed(x, "aga",
%   overlap=TRUE, case_insensitive=TRUE, omit_no_match=TRUE))
% identical(res, stri_sub_all(x,
%   stri_locate_all_fixed(x, "aga",
%     omit_no_match=TRUE, overlap=TRUE, case_insensitive=TRUE)))
% @





\subsection{Replacing pattern occurrences}

In order to replace each match with a corresponding
replacement string, we can refer to \texttt{stri\_replace\_all()}:

\begin{verbatim}<<>>=
x <- c("aga", "actg", NA, "ggAGAGAgaGAca", "agagagaga")
stri_replace_all_fixed(x, "aga", "~", case_insensitive=TRUE)
@\end{verbatim}

Note that the inputs that are not part of any match are left unchanged.
The input object is left unchanged, because it is not a replacement
function per se.

The operation is vectorised with respect to all the three arguments
(haystack, needle, replacement string),
with the usual recycling behaviour if necessary.
If a different arguments' vectorisation scheme is required,
we can set the \texttt{vectorise\_all} argument of \texttt{stri\_replace\_all()}
to \texttt{FALSE}.
Compare the following:

\begin{verbatim}<<>>=
stri_replace_all_fixed("The quick brown fox jumped over the lazy dog.",
  c("quick", "brown",      "fox", "lazy",    "dog"),
  c("slow",  "yellow-ish", "hen", "spamity", "llama"))
stri_replace_all_fixed("The quick brown fox jumped over the lazy dog.",
  c("quick", "brown",      "fox", "lazy", "dog"),
  c("slow",  "yellow-ish", "hen", "spamity", "llama"),
  vectorise_all=FALSE)
@\end{verbatim}

\noindent
Here, for every string in the \texttt{haystack}, we observe the vectorisation
independently over the \texttt{needles} and replacement strings.
Each occurrence of the 1st needle is superseded by the 1st replacement
string, then the search is repeated for the 2nd needle so as to replace
it with the 2nd corresponding replacement string, and so forth.

Moreover, \texttt{stri\_replace\_first()} and \texttt{stri\_replace\_last()}
can identify and replace the first and the last match, respectively.




\subsection{Splitting}

To  split each element in the \texttt{haystack} into substrings,
where the \texttt{needles} define the delimiters that separate
the inputs into tokens,
we call \texttt{stri\_split()}:

\begin{verbatim}<<>>=
x <- c("a,b,c,d", "e", "", NA, "f,g,,,h,i,,j,")
stri_split_fixed(x, ",", omit_empty=TRUE)
@\end{verbatim}

The result is a list of character vectors, as each string
in the \texttt{haystack}
might be split into a possibly different number of tokens.

There is also an option to limit the number of tokens
(parameter \texttt{n}).


% stri_split_fixed(x, ",", n=3)  # stringr compatibility mode
% stri_split_fixed(x, ",", n=3, tokens_only=TRUE, omit_empty=TRUE)






%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% \clearpage

\section{Regular expressions}\label{Sec:regex}

Regular expressions (regexes) provide us with a concise
grammar for defining systematic patterns which can be sought in character
strings. Examples of such patterns include:
% \begin{enumerate}
specific fixed substrings,
emojis of any kind,
stand-alone sequences of lower-case Latin letters (``words''),
substrings that can be interpreted as real numbers (with or without fractional part, also in scientific notation),
telephone numbers,
email addresses, or
URLs.
% \end{enumerate}

Theoretically, the concept of regular pattern matching
dates back to the so-called regular languages and finite state
automata \citep{kleene},
see also \citep{hopcroftullman,automata}.
Regexes in the form as we know today have already been present
in one of the pre-Unix implementations of the command-line text
editor \textit{qed} (\citealp{qed}; the predecessor of the well-known \textit{sed}).

Base  {R} gives access to two different regex matching engines
(via functions such as \texttt{gregexpr()} and \texttt{grep()},
see Table~\ref{Tab:oldstringr}):
\begin{itemize}
\item {ERE}\footnote{Via the \textit{TRE} library
(\url{https://github.com/laurikari/tre/}).}
(extended regular expressions that conform
to the POSIX.2-1992 standard);
used by default,
\item {PCRE}\footnote{Via the \textit{PCRE2}
library (\url{https://www.pcre.org/}).}
({Perl}-compatible regular expressions);
activated when \texttt{perl=TRUE} is set.
\end{itemize}
Other matchers are implemented in the \textit{ore}
(\citealp{ore}; via the \textit{Onigmo} library)
and \textit{re2r} (\citealp{re2r}; \textit{RE2}) packages.
% https://cran.r-project.org/web/packages/ore/index.html
% https://github.com/qinwf/re2r


\textit{Stringi}, on the other hand, provides access to the regex engine
implemented in \textit{ICU}, which was inspired
by {Java}'s \textit{util.regex}
in \textit{JDK 1.4}. Their syntax is mostly compatible with that of \textit{PCRE},
although certain more advanced facets might not be supported (e.g., recursive
patters). On the other hand, \textit{ICU} regexes fully conform to the
Unicode Technical Standard \#18 \citep{uts18:regex} and hence provide
comprehensive support for Unicode.


It is worth noting that most programming languages
as well as advanced text editors and development environments (including
\textit{Kate}, \textit{Eclipse}, \textit{VSCode}, and \textit{RStudio})
support finding or replacing patters with regexes.
Therefore, they should be amongst the instruments
at every data scientist's disposal.
One general introduction to regexes is \citep{friedl}.
% Some general topics are also covered in the R manual, see \texttt{?regex}.
The \textit{ICU} flavour is summarised at
\url{https://unicode-org.github.io/icu/userguide/strings/regexp.html}.






Below we provide a concise yet comprehensive introduction
to the topic from the perspective of the \textit{stringi} package users.
This time we will use the pattern search routines whose names
end with the \texttt{*\_regex()} suffix.
Apart from \texttt{stri\_detect\_regex()}, \texttt{stri\_locate\_all\_regex()},
and so forth, in Section~\ref{Sec:Capturing} we introduce
\texttt{stri\_match\_all\_regex()}.
Moreover, Table~\ref{Tab:regex_opts} lists the available options
for the regex engine.


% string search functions described in Section~\ref{Sec:fixed},




\begin{table}[t!]
\centering

\begin{tabularx}{1.0\linewidth}{p{4.6cm}X}
\toprule
\bfseries{Option}            &\bfseries Purpose \\
\midrule
\texttt{case\_insensitive}\newline
[regex flag \texttt{(?i)}] & logical; defaults to \texttt{FALSE}; whether to enable (full) case-insensitive matching  \\
\midrule
\texttt{comments}\newline
[regex flag \texttt{(?x)}] & logical; defaults to \texttt{FALSE}; whether to allow white spaces and comments within patterns  \\
\midrule
\texttt{dot\_all}\newline
[regex flag \texttt{(?s)}] & logical; defaults to \texttt{FALSE}; if set, ``\texttt{.}'' matches line terminators; otherwise its matching stops at a line end  \\
\midrule
\texttt{literal} & logical; defaults to \texttt{FALSE}; whether to treat the entire pattern as a literal string; note that in most cases the code-pointwise string search facilities
(\texttt{*\_fixed()} functions described in Section~\ref{Sec:fixed}) are faster
\\
\midrule
\texttt{multi\_line}\newline
[regex flag \texttt{(?m)}] & logical; defaults to \texttt{FALSE}; if set, ``\texttt{\$}'' and ``\texttt{\textasciicircum}'' recognise line terminators within a string; otherwise, they match only at start and end of the input \\
\midrule
\texttt{unix\_lines} & logical; defaults to \texttt{FALSE}; when enabled, only the Unix line ending, i.e., U+000A, is honoured as a terminator by ``\texttt{.}'', ``\texttt{\$}'', and ``\texttt{\textasciicircum}''\\
\midrule
\texttt{uword}\newline
[regex flag \texttt{(?w)}] & logical; defaults to \texttt{FALSE}; whether to use the Unicode definition of word boundaries (see Section~\ref{Sec:BoundaryAnalysis}), which are quite different from the traditional regex word boundaries\\
\midrule
\texttt{error\_on\_unknown\_escapes} & logical; defaults to \texttt{FALSE}; whether unrecognised backslash-escaped characters trigger an error; by default,  unknown backslash-escaped ASCII letters represent themselves \\
\midrule
\texttt{time\_limit} & integer; processing time limit for match operations in $\sim$milliseconds
(depends on the CPU speed);
0 for no limit (the default) \\
\midrule
\texttt{stack\_limit} & integer; maximal size, in bytes, of the heap storage available
for the matcher's backtracking stack; setting a limit is desirable if poorly
written regexes are expected on input; 0 for no limit (the default) \\
\bottomrule
\end{tabularx}

\caption{\label{Tab:regex_opts} Options for the regular expressions
search engine, see \texttt{stri\_opts\_regex()}.}
\end{table}



\subsection{Matching individual characters}\label{Sec:RegexIndividualChars}

We begin by discussing different ways to define character sets.
In this part, determining the length of all matching substrings
will be quite straightforward.

The following characters have special
meaning to the regex engine:
\[
\text{
  \texttt{.}\quad
  \textbackslash{}\quad
  \texttt{|}\quad
  \texttt{(}\quad
  \texttt{)}\quad
  \texttt{[}\quad
%    \texttt{]}
  \texttt{\{}\quad
  \texttt{\}}\quad
  \texttt{\^{}}\quad
  \texttt{\$}\quad
  \texttt{*}\quad
  \texttt{+}\quad
  \texttt{?}\quad
}
\]

Any regular expression that does not contain the above
behaves like a fixed pattern:

\begin{verbatim}<<>>=
stri_count_regex("spam, eggs, spam, bacon, sausage, and spam", "spam")
@\end{verbatim}

There are hence 3 occurrences of a pattern that is comprised
of 4 code points, ``\texttt{s}'' followed by ``\texttt{p}'',
then by ``\texttt{a}'', and ending with ``\texttt{m}''.

However, this time the case insensitive mode fully
supports Unicode matching\footnote{%
This does not mean, though, that it considers canonically
equivalent strings as equal,
see Section~\ref{Sec:Equivalence} for a discussion and a workaround.}:
% matching strings may be of different lengths.
% stri_detect_regex("a\u0328", "ą")
% stri_detect_regex("ą", "a\u0328")

\begin{verbatim}<<>>=
stri_detect_regex("groß", "GROSS", case_insensitive=TRUE)
@\end{verbatim}

If we wish to include a special character as part of a regular expression --
so that it is treated literally -- we will need to escape it with  a backslash,
``\textbackslash''. Yet, the backlash itself
has a special meaning to {R}, see \texttt{help("Quotes")},
therefore it needs to be preceded by another backslash.

\begin{verbatim}<<>>=
stri_count_regex("spam...", "\\.")   # "\\" is a way to input a single \
@\end{verbatim}

In other words, the {R} string \texttt{"\textbackslash\textbackslash."}
is seen by the regex engine as ``\texttt{\textbackslash.}'' and interpreted
as the dot character (literally). Alternatively,
since {R} 4.0 we can also input the so-called literal strings
like \texttt{r"(\textbackslash.)"}.


\paragraph{Matching any character.}
The (unescaped) dot, ``\texttt{.}'', matches any code point except the newline.

\begin{verbatim}<<>>=
x <- "Ham, spam,\njam, SPAM, eggs, and spam"
stri_extract_all_regex(x, "..am", case_insensitive=TRUE)
@\end{verbatim}

The above matches non-overlapping length-4 substrings that
end with ``\texttt{am}''.

The dot's insensitivity to the newline character is motivated
by the need to maintain the compatibility with tools such as \textit{grep}
(when searching within text files in a line-by-line manner).
This behaviour can be altered by setting the \texttt{dot\_all} option to \texttt{TRUE}.

\begin{verbatim}<<>>=
stri_extract_all_regex(x, "..am", dot_all=TRUE, case_insensitive=TRUE)
@\end{verbatim}



\paragraph{Defining character sets.}
Sets of characters can be introduced by enumerating
their members within a pair of
square brackets.
For instance, ``\texttt{[abc]}'' denotes the set $\{\mathtt{a},\mathtt{b},\mathtt{c}\}$
-- such a regular expression matches one (and only one) symbol from this set.
Moreover, in:


\begin{verbatim}<<>>=
stri_extract_all_regex(x, "[hj]am")
@\end{verbatim}


\noindent
the ``\texttt{[hj]am}'' regex matches:
``\texttt{h}'' or ``\texttt{j}'', followed by ``\texttt{a}'', followed by ``\texttt{m}''.
In other words, \texttt{"ham"} and \texttt{"jam"}
are the only two strings that are matched by this pattern
(unless matching is done case-insensitively).


% \begin{wazne}
The following characters, if used within square brackets, may be treated
non-literally:
\[
\text{
  \textbackslash{}\quad
  \texttt{[}\quad
  \texttt{]}\quad
  \texttt{\^{}}\quad
  \texttt{{}-{}}\quad
  \texttt{\&}\quad
}
\]
Therefore, to include them as-is in a character set, the
backslash-escape must be used.
For example, ``\texttt{[\textbackslash[\textbackslash]\textbackslash\textbackslash]}'' matches
the backslash or a square bracket.

\paragraph{Complementing sets.}
Including ``\texttt{\^{}}'' after the opening square bracket denotes the set complement.
Hence, ``\texttt{[\^{}abc]}'' matches any code point except ``\texttt{a}'',
``\texttt{b}'', and ``\texttt{c}''.
Here is an example where we seek any substring that consists of 3 non-spaces.

\begin{verbatim}<<>>=
x <- "Nobody expects the Spanish Inquisition!"
stri_extract_all_regex(x, "[^ ][^ ][^ ]")
@\end{verbatim}



\paragraph{Defining Code Point Ranges.}
Each Unicode code point can be referenced by its unique numeric identifier,
see Section~\ref{Sec:codepoints}  for more details.
For instance, ``\texttt{a}'' is assigned code U+0061 and ``\texttt{z}'' is mapped to U+007A.
In the pre-Unicode era (mostly with regards to the ASCII codes, $\le$ U+007F,
representing English letters, decimal digits, some punctuation characters,
and a few control characters),
we were used to relying on specific code ranges; e.g.,
``\texttt{[a-z]}'' denotes the set comprised of all
characters with codes between U+0061 and U+007A, i.e., lowercase letters
of the English (Latin) alphabet.

\begin{verbatim}<<>>=
stri_extract_all_regex("In 2020, Gągolewski had fun once.", "[0-9A-Za-z]")
@\end{verbatim}

% And it was awful :)


The above pattern denotes a union of 3 code ranges:
digits and ASCII upper- and lowercase letters.

Nowadays, in the processing of text in natural languages, this
notation should rather be avoided. Note the missing ``\texttt{ą}''
(Polish ``\texttt{a}'' with ogonek) in the result.


\paragraph{Using predefined character sets.}
Each code point is assigned a unique general category,
which can be thought of as a character's class,
see \citep{usa44:ucd}.
Sets of characters from each category can be referred to,
amongst others, by using the ``\texttt{\textbackslash{}p\{category\}}''
(or, equivalently, ``\texttt{[\textbackslash{}p\{category\}]}'') syntax:

% \begin{CJK*}{UTF8}{bsmi}
\begin{verbatim}<<>>=
x <- "aąbßÆAĄB你123,.;'! \t-+=[]©←→”„²³¾"
p <- c("\\p{L}", "\\p{Ll}", "\\p{Lu}", "\\p{N}", "\\p{P}", "\\p{S}")
structure(stri_extract_all_regex(x, p), names=p)
@\end{verbatim}
% \end{CJK*}

The above yield a match to: arbitrary letters, lowercase letters, uppercase letters,
numbers, punctuation marks, and symbols, respectively.

% stri_extract_all_regex(x, "\\p{L}")   # letter (equivalently: [\p{L}])
% stri_extract_all_regex(x, "\\p{Ll}")  # lowercase letter
% stri_extract_all_regex(x, "\\p{Lu}")  # uppercase letter
% stri_extract_all_regex(x, "\\p{N}")   # number
% stri_extract_all_regex(x, "\\p{P}")   # punctuation
% stri_extract_all_regex(x, "\\p{S}")   # symbol

Characters' binary properties and scripts can also be referenced in a similar manner.
Some other noteworthy classes include:

% \begin{CJK*}{UTF8}{bsmi}
\begin{verbatim}<<>>=
p <- c("\\w", "\\d", "\\s")
structure(stri_extract_all_regex(x, p), names=p)
@\end{verbatim}
% \end{CJK*}

These give: word characters, decimal digits (``\texttt{\textbackslash{}p\{Nd\}}''),
and spaces (``\texttt{[\textbackslash{}t\textbackslash{}n\textbackslash{}f\textbackslash{}r\textbackslash{}p\{Z\}]}''),
in this order.

Moreover, e.g., the upper-cased ``\texttt{\textbackslash{}P\{category\}}'' and
``\texttt{\textbackslash{}W}'' are equivalent to
``\texttt{[\^{}\textbackslash{}p\{category\}]}'' and
``\texttt{[\^{}\textbackslash{}w]}'', respectively, i.e.,
denote their complements.


% stri_extract_all_regex(z, "\\p{WHITE_SPACE}") # spaces (Unicode property)


\paragraph{Avoiding POSIX classes.}
The use of the POSIX-like character classes should be avoided,
because they are generally not well-defined.

In particular, in POSIX-like regex engines, ``\texttt{[:punct:]}''
stands for the character class corresponding to the \texttt{ispunct()}
function in {C} (see ``\texttt{man 3 ispunct}'' on Unix-like systems).
According to ISO/IEC 9899:1990 (ISO C90), \texttt{ispunct()} tests for
any printing character except for the space or a character for which \texttt{isalnum()}
is true.

Base {R} with \textit{PCRE} yields on the current
author's machine:

\begin{verbatim}<<>>=
x <- ",./|\\<>?;:'\"[]{}-=_+()*&^%$€#@!`~×‒„”"
regmatches(x, gregexpr("[[:punct:]]", x, perl=TRUE))  # base R
@\end{verbatim}

% stri_sub(x, gregexpr("[^[:punct:]]", x, perl=TRUE)[[1]], length=1)

However, the details of the characters' belongingness
to this class depend on the current locale.
Therefore, the reader might obtain different results when calling the above.

\textit{ICU}, on the other hand, always gives:

\begin{verbatim}<<>>=
stri_extract_all_regex(x, "[[:punct:]]")    # equivalently: \p{P}
@\end{verbatim}

Here, \texttt{[:punct:]} is merely a synonym for \texttt{\textbackslash{}p\{P\}}.
Further, \texttt{\textbackslash{}p\{S\}} captures symbols:

\begin{verbatim}<<>>=
stri_extract_all_regex(x, "\\p{S}")         # symbols
@\end{verbatim}

% stri_extract_all_regex(x, "[^[:punct:]]")   # complement

We strongly recommend, wherever possible, the use of the portable
``\texttt{[\textbackslash{}p\{P\}\textbackslash{}p\{S\}]}''
as an alternative to the \textit{PCRE}'s ``\texttt{[:punct:]}''.



\subsection{Alternating and grouping subexpressions}

The alternation operator, ``\texttt{|}'',
matches either its left or its right branch,
for instance:

\begin{verbatim}<<>>=
x <- "spam, egg, ham, jam, algae, and an amalgam of spam, all al dente"
stri_extract_all_regex(x, "spam|ham")
@\end{verbatim}

``\texttt{|}'' has a very low precedence. Therefore, if we wish to
introduce an alternative of subexpressions,
we need to group them, e.g., between round brackets\footnote{Which have
the side-effect of creating new capturing groups, see below for a discussion.}.
For instance, ``\texttt{(sp|h)am}'' matches either
``\texttt{spam}'' or ``\texttt{ham}''.

Also, matching is always done left-to-right, on a first-come, first-served basis.
Hence, if the left branch is a subset of the right one, the latter will
never be matched.
In particular, ``\texttt{(al|alga|algae)}'' can only match ``\texttt{al}''.
To fix this, we can write ``\texttt{(algae|alga|al))}''.


\paragraph{Non-grouping parentheses.}
Some parenthesised subexpressions -- those in which the opening bracket is followed by the question mark -- have a distinct meaning.
In particular, ``\texttt{(?\#...)}'' denotes a free-format comment
that is ignored by the regex parser:

\begin{verbatim}<<>>=
stri_extract_all_regex(x,
  "(?# match 'sp' or 'h')(sp|h)(?# and 'am')am|(?# or match 'egg')egg")
@\end{verbatim}

\noindent
Nevertheless, constructing more sophisticated regexes by concatenating
subfragments thereof may sometimes be more readable:

\begin{verbatim}<<>>=
stri_extract_all_regex(x,
  stri_join(
      "(sp|h)",   # match either 'sp' or 'h'
      "am",       # followed by 'am'
    "|",            # ... or ...
      "egg"       # just match 'egg'
))
@\end{verbatim}


What is more, e.g., ``\texttt{(?i)}'' enables the \texttt{case\_insensitive}
mode.

\begin{verbatim}<<>>=
stri_count_regex("Spam spam SPAMITY spAm", "(?i)spam")
@\end{verbatim}

For more regex flags, we kindly refer the reader to Table~\ref{Tab:regex_opts} again.




\subsection{Quantifiers}

More often than not, a variable number of
instances of the same subexpression needs to be captured
or its presence should be made optional.
This can be achieved by means of the following quantifiers:
\begin{itemize}
\item ``\texttt{?}'' matches 0 or 1 times;
\item ``\texttt{*}'' matches 0 or more times;
\item ``\texttt{+}'' matches 1 or more times;
\item ``\texttt{\{n,m\}}'' matches between \texttt{n} and \texttt{m} times;
\item ``\texttt{\{n,\}}'' matches at least \texttt{n} times;
\item ``\texttt{\{n\}}'' matches exactly \texttt{n} times.
\end{itemize}
These operators are applied to the preceding atoms.
For example, ``\texttt{ba+}'' captures
\texttt{"ba"}, \texttt{"baa"}, \texttt{"baaa"}, etc., but not \texttt{"b"} alone.


By default, the quantifiers are greedy -- they match the
repeated subexpression as many times as possible. The ``\texttt{?}'' suffix
(hence, quantifiers such as ``\texttt{??}'', ``\texttt{*?}'', ``\texttt{+?}'', and so forth) tries with
as few occurrences as possible (to obtain a match still).


\begin{verbatim}<<>>=
x <- "sp(AM)(maps)(SP)am"
stri_extract_all_regex(x,
  c("\\(.+\\)",    # [[1]] greedy
    "\\(.+?\\)",   # [[2]] lazy
    "\\([^)]+\\)"  # [[3]] greedy (but clever)
))
@\end{verbatim}

The first regex is greedy: it matches an opening bracket,
then as many characters as possible (including ``\texttt{)}'')
that are followed by a closing bracket.
The two other patterns terminate as soon as the first closing
bracket is found.

% \ifnotJSSversion
\begin{verbatim}<<>>=
stri_extract_first_regex("spamamamnomnomnomammmmmmmmm",
  c("sp(am|nom)+",             "sp(am|nom)+?",
    "sp(am|nom)+?m*",          "sp(am|nom)+?m+"))
@\end{verbatim}
% \fi


Let us stress that the quantifier is applied to the subexpression
that stands directly before it. Grouping parentheses can be used in case
they are needed.

\begin{verbatim}<<>>=
stri_extract_all_regex("12, 34.5, 678.901234, 37...629, ...",
  c("\\d+\\.\\d+", "\\d+(\\.\\d+)?"))
@\end{verbatim}

Here, the first regex matches digits, a dot, and another series of digits.
The second one finds digits which are possibly (but not necessarily)
followed by a dot and a digit sequence.





\paragraph{Performance notes.}
\textit{ICU}, just like \textit{PCRE}, uses a nondeterministic finite automaton-type
algorithm. Hence, due to backtracking, some ill-defined regexes can lead to
exponential matching times (e.g., ``\texttt{(a+)+b}'' applied on \texttt{"aaaa...aaaaac"}).
If such patterns are expected, setting the \texttt{time\_limit} or \texttt{stack\_limit}
option is recommended.

\begin{verbatim}<<time-limit, cache=TRUE, error=TRUE>>=
system.time(tryCatch({
  stri_detect_regex("a" %s*% 1000 %s+% "c", "(a+)+b", time_limit=1e5)
}, error=function(e) cat("stopped.")))
@\end{verbatim}


Nevertheless, oftentimes such regexes can be naturally
reformulated to  fix the underlying issue.
The \textit{ICU} User Guide on Regular Expressions also recommends using
possessive quantifiers (``\texttt{?+}'', ``\texttt{*+}'', ``\texttt{++}'', and so on),
which match as many times as possible but, contrary to
the plain-greedy ones, never backtrack when they happen to consume too much data.

See also the \textit{re2r} (a wrapper around the \textit{RE2} library;
\citealp{re2r}) package's
documentation and the references therein for a discussion.




\subsection{Capture groups and references thereto}\label{Sec:Capturing}

Round-bracketed subexpressions carry one additional
characteristic: they form the so-called capture groups that can
be extracted separately or be referred to in other parts of the same regex.




\paragraph{Extracting capture group matches.}
The above is evident when we use the
versions of \texttt{stri\_extract()} that are sensitive to the presence
of capture groups:


\begin{verbatim}<<>>=
x <- "name='Sir Launcelot', quest='Seek the Grail', favecolour='blue'"
stri_match_all_regex(x, "(\\w+)='(.+?)'")
@\end{verbatim}

The findings are presented in a matrix form. The first column
gives the complete matches, the second column stores the matches to the
first capture group, and so forth.
% this was introduced in string
% base R regmatches return a transposed version of these


If we just need the grouping part of ``\texttt{(...)}'', i.e.,
without the capturing feature,
``\texttt{(?:...)}'' can be applied.
Also, named capture groups defined like
``\texttt{(?<name>...)}'' are fully supported
since version 1.7.1 of our package (for historical notes see
\citealp{namedCapture}).

\begin{verbatim}<<>>=
stri_match_all_regex(x, "(?:\\w+)='(?<value>.+?)'")
@\end{verbatim}



\paragraph{Locating capture group matches.}
The \texttt{capture\_groups} attribute in \texttt{stri\_locate\_*\_regex}
enables us to pinpoint the matches to the parenthesised subexpressions
as well:

\begin{verbatim}<<>>=
stri_locate_all_regex(x, "(?<key>\\w+)='(?<value>.+?)'",
  capture_groups=TRUE, get_length=TRUE)
@\end{verbatim}

\noindent
Note that each item in the resulting list
is equipped with a \texttt{"capture\_groups"} attribute.
For instance,
\texttt{attr(result[[1]], "capture\_groups")[[2]]}
extracts the locations of the matches to the 2nd capture group
in the first input string.

\paragraph{Replacing with capture group matches.}
Matches to particular capture groups can be recalled in replacement strings
when using \texttt{stri\_replace()}.
Here, the match in its entirety is denoted with ``\texttt{\$0}'',  then
``\texttt{\$1}'' stores whatever was caught by the first capture group,
``\texttt{\$2}'' is the match to the second capture group, etc.
Moreover, ``\texttt{\textbackslash{}\$}'' gives the dollar-sign.


\begin{verbatim}<<>>=
stri_replace_all_regex(x, "(\\w+)='(.+?)'", "$2 is a $1")
@\end{verbatim}

Named capture groups can be referred to too:

\begin{verbatim}<<>>=
stri_replace_all_regex(x, "(?<key>\\w+)='(?<value>.+?)'",
  "${value} is a ${key}")
@\end{verbatim}

\paragraph{Back-referencing.}
Matches to capture groups can also be part of the regexes themselves.
For example, ``\texttt{\textbackslash{}1}'' denotes whatever
has been consumed by the first capture group.

Even though, in general, parsing {HTML} code with regexes is
not recommended, let us consider the following examples:

\begin{verbatim}<<>>=
stri_extract_all_regex("<strong><em>spam</em></strong><code>eggs</code>",
  c("<[a-z]+>.*?</[a-z]+>", "<([a-z]+)>.*?</\\1>"))
@\end{verbatim}

% stri_extract_all_regex(x, "<(?<tag>[a-z]+)>.*?</\\k<tag>>")

The second regex guarantees that the match will include all characters
between the opening \texttt{<tag>} and the corresponding (not: any)
closing \texttt{</tag>}.
Named capture groups can be referenced using the
\texttt{\textbackslash{}k<name>} syntax
(the angle brackets are part of the token), as in, e.g.,
``\texttt{<(?<tagname>[a-z]+)>.*?</\textbackslash{}k<tagname>>}''.


% \bigskip DONE-implemented
% On a side note, currently \textit{ICU} does not support the extraction
% of names of named capture groups, see however \citep{namedCapture}
% for a discussion.



\subsection{Anchoring}

Lastly, let us mention the ways to match a pattern
at a given abstract position within a string.

\paragraph{Matching at the beginning or end of a string.}
``\texttt{\^{}}'' and ``\texttt{\$}''  match, respectively,
start and end of the string
(or each line within a string, if the \texttt{multi\_line} option is set to \texttt{TRUE}).

\begin{verbatim}<<>>=
x <- c("spam egg", "bacon spam", "spam", "egg spam bacon", "sausage")
p <- c("spam", "^spam", "spam$", "spam$|^spam", "^spam$")
structure(outer(x, p, stri_detect_regex), dimnames=list(x, p))
@\end{verbatim}

The 5 regular expressions match ``\texttt{spam}'', respectively,
anywhere within the string, at the beginning,
at the end, at the beginning or end,
and in strings that are equal to the pattern itself.

% stri_detect_regex(x, "spam")           # 'spam' wherever
% stri_detect_regex(x, "^spam")          # begins with 'spam'
% stri_detect_regex(x, "spam$")          # ends with 'spam'
% stri_detect_regex(x, "spam$|^spam")    # begins or ends with 'spam'
% stri_detect_regex(x, "^spam$")         # 'spam' only


\paragraph{Matching at word boundaries.}
Furthermore, ``\texttt{\textbackslash{}b}'' matches
at a ``word boundary``, e.g., near spaces, punctuation marks,
or at the start/end of a string (i.e., wherever there is a transition
between a word, ``\texttt{\textbackslash{}w}'', and a non-word character,
``\texttt{\textbackslash{}W}'', or vice versa).

In the following example, we match
all stand-alone numbers\footnote{This regular expression
is provided for didactic purposes only.}:


\begin{verbatim}<<>>=
stri_extract_all_regex("12, 34.5, J23, 37.629cm", "\\b\\d+(\\.\\d+)?+\\b")
@\end{verbatim}

Note the possessive quantifier, ``\texttt{?+}'':
try matching a dot and a sequence of digits,
and if it is present but not followed by a word boundary,
do not retry by matching a word boundary only.



\paragraph{Looking behind and ahead.}
There are also ways to guarantee that a pattern occurrence
begins or ends with a match to some subexpression:
``\texttt{(?<=...)...}'' is the so-called  look-behind, whereas
``\texttt{...(?=...)}'' denotes the look-ahead.
Moreover, ``\texttt{(?<!...)...}'' and ``\texttt{...(?!...)}'' are
their negated (``negative look-behind/ahead'') versions.



\begin{verbatim}<<>>=
stri_extract_all_regex("I like spam, spam, eggs, and spam.",
  c("\\w+(?=[,.])", "\\w++(?![,.])"))
@\end{verbatim}

The first regex captures words that end with ``\texttt{,}'' or ``\texttt{.}''.
The second one matches words that end neither with ``\texttt{,}'' nor ``\texttt{.}''.




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\section{Collation}\label{Sec:collator}



Historically, code-pointwise comparison had been used in most string comparison
activities, especially when strings in ASCII (i.e., English) were
involved. However, nowadays %(in the ``Internet era'')
this does not necessarily constitute the most suitable
approach to the processing of natural-language texts.
In particular, a code-pointwise matching
neither takes accented and conjoined letters nor ignorable punctuation and case
into account.
% see Section~\ref{Sec:collator} for more details and an NLP-aware solution.



The \textit{ICU} Collation Service\footnote{See the \textit{ICU} User Guide on {Collation},
\url{https://unicode-org.github.io/icu/userguide/collation/}.}
provides the basis for string comparison activities  such as
string sorting and searching, or determining if two strings are equivalent.
This time, though, due to its conformance to
the Unicode Collation Algorithm \citep{uts10:collation},
% (see also ISO/IEC 14651:2016),
we may expect that the generated results
will meet the requirements of the culturally correct
natural language processing in any locale.





\subsection{Locales}

String collation is amongst many locale-sensitive operations  available
in \textit{stringi}. Before proceeding any further, we should
first discuss how we can parameterise the \textit{ICU} services
so as to deliver the results that reflect the expectations
of a specific user community, such as the speakers of different languages
and their various regional variants.

\paragraph{Specifying locales.}
A locale specifier\footnote{%
Locale specifiers in \textit{ICU} are platform-independent.
This is not the case for their base-{R} counterparts, see
\texttt{help("locales")}, e.g., we have \texttt{"Polish\_Poland"} on Windows
vs~\texttt{"pl\_PL"} on Linux.}
is of the form
\texttt{"Language"}, \texttt{"Language\_Country"}, or \texttt{"Language\_Country\_Variant"},
where:
\begin{itemize}
\item
\texttt{Language} is, most frequently, a two- or three-letter code that conforms to
the ISO-639-1 or ISO-630-2 standard, respectively;
e.g., \texttt{"en"} or \texttt{"eng"} for English, \texttt{"es"} or \texttt{"spa"}
for Spanish, \texttt{"zh"} or \texttt{"zho"} for Chinese, and \texttt{"mas"} for Masai
(which lacks the corresponding two-letter code);
however, more specific language identifiers may also be
available, e.g., \texttt{"zh\_Hans"} for Simplified-
and \texttt{"zh\_Hant"} for Traditional-Chinese
or \texttt{"sr\_Cyrl"} for Cyrillic- and \texttt{"sr\_Latn"} for Latin-Serbian;


\item
\texttt{Country} is a two-letter code following the ISO-3166 standard
that enables different language conventions within the same language;
e.g., the US-English (\texttt{"en_US"}) and Australian-English (\texttt{"en_AU"})
not only observe some differences in spelling and vocabulary but also
in the units of measurement;

\item
\texttt{Variant} is an identifier indicating a preference towards
some convention within the same country; e.g., \texttt{"de_DE_PREEURO"}
formats currency values using the pre-2002 Deutsche Mark (DEM).
\end{itemize}
Moreover,  following the
``\texttt{@}'' symbol, semicolon-separated ``\texttt{key=value}'' pairs
can be appended to the locale specifier, in order to
customise some locale-sensitive services even further
(see below for an example using ``\texttt{@collation=phonebook}''
and Section~\ref{Sec:datetime} for ``\texttt{@calendar=hebrew}'', amongst others).


{\color{red}

}
%
% (GNU/Linux)	pl_PL.iso-8859-2
% (GNU/Linux)	Polish_Poland.1250
%





\paragraph{Listing locales.}
To list the available locale identifiers, we call \texttt{stri\_locale\_list()}.

\begin{verbatim}<<>>=
length(stri_locale_list())
@\end{verbatim}

\noindent
As the number of supported locales is very high, here we shall
display only 5 randomly chosen ones:

\begin{verbatim}<<echo=-1>>=
set.seed(514678)
sample(stri_locale_list(), 5)
@\end{verbatim}



\paragraph{Querying for locale-specific services.}
The availability of locale-specific services can only be determined during
the request for a particular resource\footnote{For more details,
see the \textit{ICU} User Guide on {Locales},
\url{https://unicode-org.github.io/icu/userguide/locale/}.},
which may depend on the \textit{ICU} library version
actually in use as well as the way the \textit{ICU} Data Library (\textit{icudt})
has been packaged. Therefore, for maximum portability,
it is best to rely on the \textit{ICU} library bundle that
is shipped with \textit{stringi}.
This is the case on Windows and macOS, whose users typically download the
pre-compiled versions of the package from CRAN.
However, on various flavours of GNU/Linux and other Unix-based systems,
the system \textit{ICU} is used more eagerly\footnote{
See, e.g., software packages
\texttt{libicu-dev} on Debian/Ubuntu or \texttt{libicu-devel} on RHL/Fedora/OpenSUSE.
For more details regarding the configure/build process of \textit{stringi},
refer to the \texttt{INSTALL} file.}.
To force building \textit{ICU} from sources, we may call:

\begin{verbatim}<<eval=FALSE>>=
install.packages("stringi", configure.args="--disable-pkg-config")
@\end{verbatim}

Overall, if a requested service is unavailable
in a given locale, the best possible match is returned.


\paragraph{Default locale.}
Each locale-sensitive operation in \textit{stringi} selects the current
default locale if no locale has been explicitly requested,
i.e., when a function's \texttt{locale} argument (see Table~\ref{Tab:collator_opts})
is left alone in its ``\texttt{NULL}'' state.
The default locale is initially set to match the system locale on the current
platform, and may be changed with \texttt{stri\_locale\_set()}, e.g.,
in the very rare case of improper automatic locale detection.

As we have stated in the introduction, in this paper we use:

\begin{verbatim}<<>>=
stri_locale_get()
@\end{verbatim}

\noindent
i.e., the Australian-English locale
(which formats dates like ``29 September 2021'' and
uses metric units of measurement).

% locales in base R -- very problematic
%
% Sys.getlocale
%
% Sys.setlocale
%
% no per-call basis
%
% might be not installed
%
% different identifiers on Windows







\subsection{Testing string equivalence}\label{Sec:Equivalence}



% Canonical and Compatibility Equivalence -> https://unicode.org/reports/tr15/
In Unicode, some characters may have multiple representations.
For instance, ``LATIN SMALL LETTER A WITH OGONEK'' (``ą'') can be stored
as a single code point U+0105 or as a sequence
that is comprised of the letter ``LATIN SMALL LETTER A'', U+0061, and
the ``{COMBINING OGONEK}'', U+0328 (when rendered properly, they
should appear as if they were identical glyphs).
This is an example of canonical equivalence of strings.

Testing for the Unicode equivalence between strings
can be performed by calling \texttt{\%s==\%} and, more generally,
\texttt{stri\_cmp\_equiv()}, or their negated versions,
\texttt{\%s!=\%} and \texttt{stri\_cmp\_nequiv()}.

In the example below we have: a followed by ogonek (two code points)
vs a with ogonek (single code point).

\begin{verbatim}<<>>=
"a\u0328" %s==% "ą"             # a, ogonek == a with ogonek
@\end{verbatim}

% stri_cmp_equiv("a\u0328", "ą")  # the same


There are also functions for removing and indicating
duplicated elements in a character vector:

\begin{verbatim}<<>>=
x <- c("Gągolewski", "Gagolewski", "Ga\u0328golewski")
stri_unique(x)
stri_duplicated(x)  # from_last=FALSE
@\end{verbatim}

Moreover, \texttt{stri\_duplicated\_any()}
returns the index of the first non-unique element.






\subsection{Linear ordering of strings}


% https://www.elastic.co/guide/en/elasticsearch/guide/current/sorting-collations.html

Operators such that \texttt{\%s<\%}, \texttt{\%<=\%}, etc.,
and the corresponding functions
\texttt{stri\_cmp\_lt()} (``less than''),
\texttt{stri\_cmp\_le()} (``less than or equal''), etc.,
implement locale-sensitive linear orderings of strings.
Moreover, \texttt{stri\_sort()} returns the lexicographically-sorted
version of a given input vector, \texttt{stri\_order()} yields
the corresponding (stable) ordering permutation,
and \texttt{stri\_rank()} ranks strings within a vector.


% contextual e.g., Slovak ch h c

For instance, here is a comparison in the current default locale
(Australian-English):

\begin{verbatim}<<>>=
"chaotic" %s<% "hard"  # c < h
@\end{verbatim}

Similar comparison in Polish:

\begin{verbatim}<<>>=
stri_cmp_lt("chłodny", "hardy", locale="pl_PL")  # c < h
@\end{verbatim}

And now for something completely different -- the Slovak language:

\begin{verbatim}<<>>=
stri_cmp_lt("chladný", "hladný", locale="sk_SK") # ch > h
@\end{verbatim}

% stri_cmp("chladný", "hladný", locale="sk_SK")    # -1,0,1 encode <,=,>


This is an example of the locale-aware comparison
that is context-sensitive
and which goes beyond the simple code-pointwise comparison.
In the example above, a contraction occurred:
in Slovak,
two code points ``\texttt{ch}'' are treated as a single entity
and are sorted after ``\texttt{h}'':


Compare the ordering of Polish and Slovak words:

\begin{verbatim}<<>>=
stri_sort(c("chłodny", "hardy", "cichy", "cenny"), locale="pl_PL")
stri_sort(c("cudný", "chladný", "hladný", "čudný"), locale="sk_SK")
@\end{verbatim}

% stri_sort(c("cudný", "chladný", "hladný"), locale="cs_CZ")


An opposite situation is called an expansion:

\begin{verbatim}<<>>=
german_k_words <- c("können", "kondensieren", "kochen", "korrelieren")
stri_sort(german_k_words, locale="de_DE")
stri_sort(german_k_words, locale="de_DE@collation=phonebook")
@\end{verbatim}

% TODO:  something in-between??

In the latter example, where we used the German phone-book order,
\texttt{"ö"} is treated as \texttt{"oe"}.


% stri_rank example with numeric=TRUE below




\subsection{Collator options}\label{Sec:collator_opts}

Table~\ref{Tab:collator_opts} lists the options
that can be passed to \texttt{stri\_opts\_collator()} via the dot-dot-dot
parameter, ``\texttt{...}'', in
all the functions that rely on the \textit{ICU} Collator.
Below we would like to attract the kind reader's attention
to some of them.

% https://unicode-org.github.io/icu/userguide/collation/ - many nice examples



\begin{table}[bt!]
\centering

\begin{tabularx}{1.0\linewidth}{lX}
\toprule
\bfseries{Option}            &\bfseries Purpose \\
\midrule
\texttt{locale}             & a string specifying the locale to use; \texttt{NULL}
(default) or \texttt{""} for the current default locale as indicated by
\texttt{stri\_locale\_get()} \\
\midrule
\texttt{strength}           & an integer in $\{1,2,3,4\}$ defining collation strength;
1 for the most permissive collation rules, 4 for the strictest ones;
defaults to 3 \\
\midrule
\texttt{uppercase\_first}    & logical; \texttt{NA} (default) orders upper
and lower
case letters in accordance to their tertiary weights, \texttt{TRUE} forces upper
case letters to sort before lower case letters, \texttt{FALSE} does the opposite \\
\midrule
\texttt{numeric}            & logical; if \texttt{TRUE}, a collation key
for the numeric value of substrings of digits is generated; this is a way to
make \texttt{"100"} ordered
after \texttt{"2"}; defaults to \texttt{FALSE} \\
\midrule
\texttt{case\_level}         & logical; if \texttt{TRUE}, an extra case level
(positioned before the third level) is generated; defaults to \texttt{FALSE} \\
\midrule
\texttt{normalisation}      & logical; if \texttt{TRUE}, then an incremental
check is performed to see whether input data are in the FCD (``fast C or D'') form;
if data are not in the FCD form, the incremental NFD normalisation is performed,
see Section~\ref{Sec:normalisation}; defaults to \texttt{FALSE}   \\
\midrule
\texttt{alternate\_shifted}  & logical; if \texttt{FALSE} (default),
all code points with non-ignorable primary weights are handled in the same way;
\texttt{TRUE} causes the code points
with primary weights that are less than or equal to the variable top value
to be ignored on the primary level and moved to the quaternary level; this can be
used to, e.g., ignore punctuation, see the examples provided \\ \midrule
\texttt{french}             & logical; \texttt{TRUE} results in secondary
weights being considered backwards, i.e., ordering according to the last accent difference
-- nowadays only used in Canadian-French; defaults to \texttt{FALSE} \\
\bottomrule
\end{tabularx}

\caption{\label{Tab:collator_opts} Options for the \textit{ICU}
Collator that can be passed to \texttt{stri\_opts\_collator()}.}
\end{table}




\paragraph{Collation strength.}
The Unicode Collation Algorithm \citep{uts10:collation}
can go beyond simple canonical equivalence:
it can treat some other (depending on the context)
differences as negligible too.

The \texttt{strength} option controls the Collator's ``attention to detail''.
For instance, it can be used to make the ligature ``ff'' (U+FB00)
compare equal to the two-letter sequence ``f{}f'':

\begin{verbatim}<<>>=
stri_cmp_equiv("\ufb00", "ff", strength=2)
@\end{verbatim}

\noindent
which is not the case at the default strength level (3).

% stri_cmp_equiv("\ufb00", "ff")

% \clearpage


Generally, four (nested) levels of inter-string differences can be distinguished:
% https://unicode-org.github.io/icu/userguide/collation/concepts.html
\begin{enumerate}
\item A primary difference -- the strongest one -- occurs where
there is a mismatch between base characters (e.g., \texttt{"a"} vs~\texttt{"b"}).

\item Some character accents can be considered a secondary difference
in many languages. However, in other ones, an accented letter is considered
a unique letter.

\item Distinguishing between upper- and lower case typically happens
on the tertiary level (see, however, the \texttt{case\_level} option).


\item If \texttt{alternate\_shifted} is \texttt{TRUE},
differences in punctuation
can be determined at the quaternary level. This is also meaningful
in the processing of Hiragana text.


\end{enumerate}

\vbox{
\paragraph{Ignoring case.}
Note which strings are deemed equivalent when
considering different collation strengths:

\begin{verbatim}<<>>=
x <- c("gro\u00df", "gross", "GROSS", "Gro\u00df", "Gross")
stri_unique(x, strength=1)                  # ß == ss, case insensitive
stri_unique(x, strength=2)                  # ß != ss, case insensitive
@\end{verbatim}
}


Hence, strength equal to 1 takes only primary differences
into account. Strength of 2 will also be sensitive to secondary differences
(distinguishes between ``ß'' and ``ss'' above), but will ignore
tertiary differences (case).

Also, introducing an extra case level yields
a case sensitive comparison that ignores secondary differences:

\begin{verbatim}<<>>=
stri_unique(x, strength=1, case_level=TRUE) # ß == ss, case sensitive
@\end{verbatim}


\paragraph{Ignoring some punctuation.}
Here are some effects of changing the  \texttt{alternate\_shifted} option,
which allows for ignoring some punctuation marks:

\begin{verbatim}<<>>=
x <- c("code point", "code-point", "codepoint", "CODE POINT", "CodePoint")
stri_unique(x, alternate_shifted=TRUE)  # strength=3
stri_unique(x, alternate_shifted=TRUE, strength=2)
@\end{verbatim}

In the latter case, all strings are considered equivalent.
Ignoring case but not punctuation yields:

\begin{verbatim}<<>>=
stri_unique(x, strength=2)
@\end{verbatim}

%
% % outer(x, x, stri_cmp, strength=2)
%
% primary secondary tertiary quaternary  equal
%
%  	A and B are equivalent (equal at all levels)
%
%  	canonically equivalent: the sequences represent essentially the same text, but with different actual sequences (see Unicode Normalisation Forms
%  	in  Section~\ref{Sec:normalisation} and \citealp{usa15:normalization})
%
% quote: The default for strength in UCA is tertiary; ???
%
% quote:. For example, setting the strength to exclude differences at Level 3 has the effect of ignoring case and compatibility format distinctions between letters when matching. Excluding differences at Level 2 has the effect of also ignoring accentual distinctions when matching.
%
%




\paragraph{Backward secondary sorting.}
The French Canadian Sorting Standard CAN/CSA Z243.4.1 (historically this had been
the default for all French locales) requires the word ordering with respect
to  the last accent difference. Such a behaviour can be applied
either by setting the French-Canadian locale or by passing the \texttt{french=TRUE}
option to the Collator.

\begin{verbatim}<<>>=
stri_sort(c("cote", "côte", "coté", "côté"), locale="fr_FR")
stri_sort(c("cote", "côte", "coté", "côté"), locale="fr_CA") # french=TRUE
@\end{verbatim}



\paragraph{Sorting numerals.}
By default, just like in base {R} and most other programming
languages, a lexicographic ordering is used: the corresponding
code points are being compared one by one, from left to right,
and once a difference
is detected, the result is returned immediately.

\begin{verbatim}<<>>=
x <- c("a1", "a2", "a11", "a1", "a99", "a10", "a100", "a2", "a9", "a2")
stri_sort(x)
@\end{verbatim}

For example, \texttt{"a99"} is ordered after \texttt{"a100"},
because \texttt{"a" == "a"} (first characters are equal)
but then \texttt{"9" > "1"} (second characters are already different).

Let us, however, note the effect of setting the \texttt{numeric} option
on the sorting of strings that involves numbers:

\begin{verbatim}<<>>=
stri_sort(x, numeric=TRUE)
@\end{verbatim}


% <<echo=-1>>=
% set.seed(123)
% slowa <- sample(readLines(
%    "https://raw.githubusercontent.com/" %s+% # złączenie napisów, zob. dalej
%    "gagolews/Programowanie_w_jezyku_R/master/wyd2/dane/PL_ispell.txt"
% )) # baza słów w języku polskim
% length(slowa)
% cat(sample(slowa, 5), sep=", ")
% print(microbenchmark::microbenchmark(
%    sort      = sort(slowa),
%    stri_sort = stri_sort(slowa),
%    times=10
% ), signif=3)
% @


Here is an example of sorting a data frame
with respect to two criteria:

\begin{verbatim}<<echo=-1>>=
set.seed(123)
X <- data.frame(a=x, b=runif(length(x)))
X[order(-stri_rank(X$a, numeric=TRUE), X$b), ]
@\end{verbatim}

The object is now ordered by the first column decreasingly
(using a ``numeric'' order) and ties are resolved based on increasing
values in the second column.


\paragraph{A note on compatibility equivalence.}
In Section~\ref{Sec:normalisation} we describe different ways to normalise
canonically equivalent code point sequences so that they are
represented by the same code points, which can account for some negligible
differences (as in the ``a with ogonek'' example above).

Apart from ignoring punctuation and case, the Unicode Standard Annex \#15 \citep{usa15:normalization}
also discusses the so-called compatibility equivalence of strings.
This is a looser form of similarity; it is observed where
there is the same abstract content, yet displayed
by means of different glyphs, for instance ``¼'' (U+00BC) vs~``\texttt{1/4}''
or ``$\mathbb{R}$'' vs~``{R}''.
In the latter case, whether these should be treated as equal,
depends on the context (e.g., this can be the set of real numbers
vs~one's favourite programming language).
Compatibility decompositions (NFKC, NFKD)
mentioned in Section~\ref{Sec:normalisation}
or other types of transliteration can be used to normalise strings so that
such differences are not accounted for.

Also, for ``fuzzy'' matching of strings,
the \textit{stringdist} package \citep{stringdist} might be helpful.


% adist, agrep, \textit{stringdist} + citation package -- "fuzzy pattern matching"
% some approximate NNs?
% \textit{stringdist} -- out of scope of stringi




%stri_cmp_equiv("\u00bc", "1/4", strength=0, alternate_shifted=TRUE)


% > stri_trans_general("a\u0328ą", "name")
% [1] "\\N{LATIN SMALL LETTER A}\\N{COMBINING OGONEK}\\N{LATIN SMALL LETTER A WITH OGONEK}"





\subsection{Searching for fixed strings revisited}

The \textit{ICU} Collator can also be utilised
where there is a need to locate the occurrences of simple textual patterns.
The counterparts of the string search functions
described in Section~\ref{Sec:fixed}
have their names ending with \texttt{*\_coll()}.
They are slower than them, but are more appropriate in NLP activities.

For instance:

\begin{verbatim}<<>>=
stri_detect_coll("Er ist so groß.", "GROSS", strength=1, locale="de_AT")
stri_detect_coll("On je chladný", "chladny", strength=1, locale="sk_SK")
@\end{verbatim}
% \end{ciekawostka}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\section{Other operations}\label{Sec:other}

In the sequel, we cover the functions that deal with
text boundary detection, random string generation,
date/time formatting and parsing, amongst others.


% \color{blue}
\subsection{Analysing text boundaries}\label{Sec:BoundaryAnalysis}

Text boundary analysis aims at locating linguistic delimiters
for the purpose of splitting text into lines,
word-wrapping, counting characters or
words, locating particular text units (e.g.,
the 3rd sentence), etc.

Generally, text boundary analysis is a locale-sensitive operation,
see \citep{usa29:segmentation}.
For example, in Japanese and Chinese, spaces are not used for
separation of words  --
a line break can occur even in the middle of a word. Nevertheless,
these languages have punctuation and diacritical marks that cannot
start or end a line, so this must also be taken into account.

The \textit{ICU} Break Iterator\footnote{See the \textit{ICU} User Guide
on {Boundary Analysis}, \url{https://unicode-org.github.io/icu/userguide/boundaryanalysis/}.}
comes in four flavours (see the \texttt{type} option
in \texttt{stri\_opts\_brkiter()}):
\texttt{character}, \texttt{work}, \texttt{line\_break}, and \texttt{sentence}.

We have access to functions such as
\texttt{stri\_count\_boundaries()},
\texttt{stri\_split\_boundaries()},
\texttt{stri\_extract\_*\_boundaries()}, and
\texttt{stri\_locate\_*\_boundaries()},
as well as their specialised
versions:
\texttt{stri\_count\_words()},
\texttt{stri\_extract\_*\_words()}, and
\texttt{stri\_split\_lines()}, amongst others.
For example:


\begin{verbatim}<<>>=
x <- "The\u00a0above-mentioned    features are useful. " %s+%
  "My hovercraft is full of eels, eggs, and spam."
@\end{verbatim}

Number of sentences:

\begin{verbatim}<<>>=
stri_count_boundaries(x, type="sentence")
@\end{verbatim}

The list of all the words:

\begin{verbatim}<<>>=
stri_extract_all_words(x)
@\end{verbatim}


% \texttt{?stri_opts_brkiter}



\subsection{Trimming, padding, and other formatting}

The following functions can be used for pretty-printing
character strings or text on the console,
dynamically generating reports (e.g.,
with \texttt{Sweave()} or \textit{knitr}; see \citealp{knitr}),
or creating text files
(e.g., with \texttt{stri\_write\_lines()}; see Section~\ref{Sec:read_lines}).



\paragraph{Padding.}
\texttt{stri\_pad()} pads strings with some character so that they
reach the desired widths (as in \texttt{stri\_width()}).
This can be used to centre, left-, or right-align a message
when printed with, e.g.,  \texttt{cat()}.


\begin{verbatim}<<>>=
cat(stri_pad("SPAMITY SPAM", width=77, side="both", pad="."))
@\end{verbatim}

% cat(stri_pad("spam", width=77, side="left"))

% <<>>=
% x <- "*" %s*% 1:3
% y <- "*" %s*% 3:1
% w <- max(stri_length(c(x, y)))
% cat(stri_join(stri_pad(x, width=w, side="left"),
%                stri_pad(y, width=w, side="left"),
%                collapse="\n", sep=" | "))
% @





\paragraph{Trimming.}
A dual operation is that of trimming from the left or right side
of strings:

\begin{verbatim}<<>>=
x <- "      spam, eggs, and lovely spam.\n"
stri_trim(x)  # side="both"
@\end{verbatim}

% stri_trim(x, pattern="[^\\n\\p{Z}\\p{P}\\p{S}]")


\paragraph{Word wrapping.}
The \texttt{stri\_wrap()} function splits each (possibly long)
string in a character vector into chunks of at most a given width.
By default, the dynamic word wrap algorithm \citep{Knuth:wrap}
that minimises the raggedness of the formatted text is used.
However, there is also an option (\texttt{cost\_exponent=0})
to use the greedy alignment,
for compatibility with the built-in \texttt{strwrap()}.

\begin{verbatim}<<echo=-1>>=
set.seed(1233)
x <- stri_rand_lipsum(1)  # random text paragraph
cat(stri_wrap(x, width=74, indent=8, exdent=4, prefix="> "), sep="\n")
@\end{verbatim}

% Note that, by default, the splitting is performed at line breaks
% (compare Section~\ref{Sec:BoundaryAnalysis}).






\paragraph{Applying string templates.}
\texttt{stri\_sprintf()} is a Unicode-aware rewrite of the built-in
\texttt{sprintf()} function. In particular, it enables formatting and
padding based on character width, not just the number of code points.
The function is also available as a binary operator \texttt{\%s\$\%},
which is similar to {Python}'s \texttt{\%} overloaded for
objects of type \texttt{str}.

\begin{verbatim}<<>>=
cat(stri_sprintf("[%6s]", c("abcd", "\u200b\u200b\u200bąß²€")), sep="\n")
@\end{verbatim}

The above guarantees that the two output strings are
of at least width of 6 (plus the square brackets).


% \ifnotJSSversion
\begin{verbatim}<<>>=
"value='%.4f'" %s$% pi  # equivalently: "value='%.4f'" %s$% list(pi)
"%s='%.*3$f'" %s$% list("pi", pi, 1:4)
@\end{verbatim}
% \fi

\subsection{Generating random strings}

Apart from \texttt{stri\_rand\_lipsum()},
which produces random-ish text paragraphs (``placeholders'' for real text),
we have access to a function that generates sequences of characters
uniformly sampled (with replacement) from a given set.

For example, here are 5 random ACTG strings of lengths from 2 to 6:

\begin{verbatim}<<echo=-1>>=
set.seed(123)
stri_rand_strings(5, 2:6, "[ACTG]")
@\end{verbatim}

% \ifnotJSSversion
Moreover:

\begin{verbatim}<<>>=
stri_rand_strings(1, 8, "[\\p{script=Katakana}&\\p{L}]")
@\end{verbatim}
% \fi

See Section~\ref{Sec:RegexIndividualChars}
and \texttt{help("stringi-search-charclass")}
for different ways to specify character sets.





% \color{blue}
\subsection{Transliterating}

Transliteration, in its broad sense, deals with the substitution
of characters or their groups for different ones, according to some
well-defined, possibly context-aware, rules.
It may be useful, amongst others, when "normalising"
pieces of strings or identifiers so that they can be more easily
compared with each other.


\paragraph{Case mapping.}
% https://www.unicode.org/versions/Unicode11.0.0/
Mapping to  upper, lower, or title case
is a language- and context-sensitive operation
that can change the total number of code points in a string.

% (character mapping may depend on its surrounding characters). https://unicode-org.github.io/icu/userguide/transforms/casemappings.html


\begin{verbatim}<<>>=
stri_trans_toupper("groß")
stri_trans_tolower("Iİ", locale="tr_TR")               # Turkish
stri_trans_totitle("ijsvrij yoghurt", locale="nl_NL")  # Dutch
@\end{verbatim}




% Also: case folding - not locale-sensitive for the purpose of comparing strings



\paragraph{Mapping between specific characters.}
When a fast 1-to-1 code point translation is required, we can call:

\begin{verbatim}<<>>=
stri_trans_char("GATAAATCTGGTCTTATTTCC", "ACGT", "tgca")
@\end{verbatim}

Here, ``\texttt{A}'', ``\texttt{C}'', ``\texttt{G}'', and ``\texttt{T}''
is replaced with
``\texttt{t}'', ``\texttt{g}'', ``\texttt{c}'', and ``\texttt{a}'', respectively.



\paragraph{General transforms.}
\texttt{stri\_trans\_general()} provides access to a wide range of text transforms
defined by \textit{ICU}, whose catalogue can be accessed by calling
\texttt{stri\_trans\_list()}.

\begin{verbatim}<<echo=-1>>=
set.seed(12345)
sample(stri_trans_list(), 9)  # a few random entries
@\end{verbatim}

For example, below we apply a transliteration chain:
first, we convert to upper case, and then we convert characters
in the Latin script to ASCII.


\begin{verbatim}<<>>=
stri_trans_general("groß© żółć La Niña köszönöm", "upper; latin-ascii")
@\end{verbatim}

% stri_trans_general("I'll come -- that's what she said.", "any-publishing")

Custom rule-based transliteration is also
supported\footnote{See the \textit{ICU} User Guide on {General Transforms}
for more details,
\url{https://unicode-org.github.io/icu/userguide/transforms/general/}.
}. It can be used, for instance, to generate different romanisations
of non-Latin alphabets.

%Deviate from the ICU rules of romanisation of Korean,
% https://en.wikipedia.org/wiki/Romanization_of_Korean
%see https://en.wikipedia.org/wiki/Revised_Romanization_of_Korean

% <<>>=
% x <- "\uC885\uB85C\uAD6C \uC0AC\uC9C1\uB3D9"
% stringi::stri_trans_general(x, "Hangul-Latin")
% id <- "
%     :: NFD;
%     \u11A8 > k;
%     \u11AE > t;
%     \u11B8 > p;
%     \u1105 > r;
%     :: Hangul-Latin;
% "
% stringi::stri_trans_general(x, id, rules=TRUE)
% @

% stri_trans_general("stringi", "latin-greek")
% stri_trans_general("Пётр Ильич Чайковский",
%     "cyrillic-latin; nfd; [:nonspacing mark:] remove; nfc")

% not locale-dependent



% It's getting hotter with these:
%
% ```{r}
% stri_trans_general("w szczebrzeszynie chrząszcz brzmi w trzcinie", "pl-pl_fonipa")
% # and now the same in the XSampa ASCII-range representation:
% stri_trans_general("w szczebrzeszynie chrząszcz brzmi w trzcinie", "pl-pl_fonipa; ipa-xsampa")
% ```

%  stri_trans_general("zażółć gęślą jaźń", "[\\p{Z}] remove")

%  stri_trans_general("Let's go... -- that's what she said.", "any-publishing")






\subsection{Parsing and formatting date and time}\label{Sec:datetime}

In base {R}, dealing with temporal data in regional
settings other than the current locale is somewhat difficult.
For instance, many will find the task of parsing the following Polish date problematic:

\begin{verbatim}<<>>=
x <- "28 września 2021 r., godz. 17:17:32"
@\end{verbatim}

\textit{stringi} connects to the \textit{ICU} date and time
services so that this becomes an easy exercise:


\begin{verbatim}<<>>=
stri_datetime_parse(x, "dd MMMM yyyy 'r., godz.' HH:mm:ss",
  locale="pl_PL", tz="Europe/Warsaw")
@\end{verbatim}

This function returns an object of class \texttt{POSIXct},
for compatibility with base {R}.
Note, however, that
\textit{ICU} uses its own format patterns\footnote{
See the \textit{ICU} User Guide on {Formatting Dates and Times},
\url{https://unicode-org.github.io/icu/userguide/format_parse/datetime/}.
}. For convenience,
\texttt{strftime()}- and \texttt{strptime()}-like
templates can be converted with \texttt{stri\_datetime\_fstr()}:

\begin{verbatim}<<>>=
stri_datetime_parse(x,
  stri_datetime_fstr("%d %B %Y r., godz. %H:%M:%S"),
  locale="pl_PL", tz="Europe/Warsaw")
@\end{verbatim}

% \ifnotJSSversion
Relative dates are also supported:

\begin{verbatim}<<>>=
stri_datetime_format(
  stri_datetime_add(stri_datetime_now(), 1, "day"), # add 1 day to 'now'
  "datetime_relative_long",              # full format, relative to 'now'
  locale="en_NZ", tz="NZ")
@\end{verbatim}
% \fi

For example, here is how we can access different calendars:

\begin{verbatim}<<>>=
stri_datetime_format(
  stri_datetime_create(2020, 1:12, 1),
  "date_long",
  locale="@calendar=hebrew")
stri_datetime_format(
  stri_datetime_create(2020, c(2, 8), c(4, 7)),
  "date_full",
  locale="ja_JP@calendar=japanese")
@\end{verbatim}

\noindent
Above we have selected the Hebrew calendar within the
English locale and the Japanese calendar in the Japanese locale.


% \texttt{he_IL@calendar=hebrew}
% \texttt{ja_JP_TRADITIONAL}

% stri_locale_info("@calendar=hebrew")

% \texttt{@calendar=hebrew}



% timezone



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\section{Input and output}\label{Sec:io}

This section deals with some more advanced topics related to the
operability of text processing applications
between different platforms. In particular, we discuss
how to assure that data read from various input connections
are interpreted in the correct manner.



\subsection{Dealing with Unicode code points}\label{Sec:codepoints}

The Unicode Standard (as well as the
Universal Coded Character Set, i.e., ISO/IEC 10646)
currently defines over 140{,}000 abstract characters together with
their corresponding code points -- integers
between 0 and 1{,}114{,}111 (or 0000${}_{16}$ and 10FFFF${}_{16}$
in hexadecimal notation, see \url{https://www.unicode.org/charts/}).
In particular, here is the number of the code points in
some popular categories (compare Section~\ref{Sec:RegexIndividualChars}),
such as letters, numbers, and the like.

\begin{verbatim}<<>>=
z <- c("\\p{L}", "\\p{Ll}", "\\p{Lu}", "\\p{N}", "\\p{P}", "\\p{S}",
  "\\w", "\\d", "\\s")
structure(stri_count_regex(stri_enc_fromutf32(
  setdiff(1:0x10ffff, c(0xd800:0xf8ff))), z), names=z)
@\end{verbatim}

Yet, most of the code points are still unallocated.
The Unicode standard is occasionally updated, e.g., the
most recent versions were supplemented with over 1{,}000 emojis.


The first 255 code points are identical to the ones defined
by ISO/IEC 8859-1 (ISO Latin-1;
``Western European''), which itself extends US-ASCII (codes $\le 127=\text{7F}{}_{16}$).
For instance, the code point that we are used to denoting as U+007A
(the ``U+'' prefix is followed by a sequence of hexadecimal digits;
7A${}_{16}$ corresponds to decimal 122) encodes the lower case letter ``z''.
To input such a code point in {R}, we write:

\begin{verbatim}<<>>=
"\u007A"  # or "\U0000007A"
@\end{verbatim}


For communicating with \textit{ICU} and other libraries,
we may need to escape a given string, for example, as follows
(recall that to input a backslash in {R},
we must escape it with another backslash).

\begin{verbatim}<<>>=
x <- "zß你好"
stri_escape_unicode(x)
@\end{verbatim}


% stri_trans_general(x, "[^\\u0000-\\u007f] any-hex") # except ASCII
% stri_trans_general(x, "[^\\u0000-\\u007f] any-hex/xml")
% stri_unescape_unicode("\\u007A")

\bigskip
It is worth noting that despite the fact that some output devices
might be unable to display certain code points correctly
(due to, e.g., missing fonts), the correctness of their
processing with \textit{stringi} is still guaranteed by \textit{ICU}.

% \ifnotJSSversion
% Here is an example of an incorrect presentation of an emoji,
% generated by a malconfigured \XeLaTeX{} engine:
%
% <<>>=
% "\U001F600" # the grinning face emoji, (:               - font unavailable
% @
%
% Nevertheless, the programmatic handling of such a code point is unaffected:
%
% <<>>=
% stri_trans_general("\U001F600", "any-name") # query the character database
% @
% \fi


% ```{r}
% stri_trans_general("ą1©,", "any-name")
% stri_trans_general("\\N{LATIN SMALL LETTER SHARP S}", "name-any")
% ```
%
%




\subsection{Character encodings}\label{Sec:encoding}

When storing strings in RAM or on the disk,
we need to decide upon the actual way
of representing the code points as sequences of bytes.
The two most popular encodings in the Unicode family are
UTF-8 and UTF-16:

\begin{verbatim}<<>>=
x <- "abz0ąß你好!"
stri_encode(x, to="UTF-8", to_raw=TRUE)[[1]]
stri_encode(x, to="UTF-16LE", to_raw=TRUE)[[1]]  # little-endian
@\end{verbatim}

{R}'s current platform-default encoding, which we shall
refer to as the native encoding, is defined via the
\texttt{LC\_CTYPE} locale category in
\texttt{Sys.getlocale()}. This is the representation assumed,
e.g., when reading data from the standard input
or from files (e.g., when \texttt{scan()} is called).
% as well as written to the output devices
% (e.g., \texttt{print()} and \texttt{cat()}).
For instance, Central European versions of Windows will assume
the ``\texttt{windows-1250}'' code page.
MacOS as well as most Linux boxes work with UTF-8 by default\footnote{
It is expected that future {R} releases will support UTF-8 natively
thanks to the Universal {C} Runtime (UCRT) that is available for Windows 10.
% https://developer.r-project.org/Blog/public/2020/05/02/utf-8-support-on-windows/index.html
}

% Character vectors in {R} resemble lists of raw-type vectors
% (each ending with byte 0x00).
All strings in {R} have an associated encoding mark
which can be read by calling \texttt{Encoding()} or, more conveniently,
\texttt{stri\_enc\_mark()}.
Most importantly, strings in ASCII, ISO-8859-1 (``\texttt{latin1}''),
UTF-8, and the native encoding can coexist.
Whenever a non-Unicode string is passed to a function in \textit{stringi},
it is silently converted to UTF-8 or UTF-16, depending on the requested
operation (some \textit{ICU} services are only available for {UTF-16} data).
Over the years, this has proven a robust, efficient, and maximally portable
design choice -- Unicode can be thought of as a superset of every other encoding.
Moreover, in order to guarantee the correctness and high performance of
the string processing pipelines, \textit{stringi} always\footnote{With a few
obvious exceptions, such as \texttt{stri\_encode()}.} outputs
UTF-8 data.


\subsection{Reading and writing text files and converting between encodings}\label{Sec:read_lines}

According to a report by W3Techs\footnote{See
\url{https://w3techs.com/technologies/cross/character_encoding/ranking}.},
as of 2021--09--28, 97.3\% of websites use UTF-8.
Nevertheless, other encodings can still be encountered.

\paragraph{Reading and writing text files.}
If we know the encoding of a text file  in advance,
\texttt{stri\_read\_lines()} can be used to read
the data in a manner similar to the built-in \texttt{readLines()} function
(but with a much easier access to encoding conversion):

For instance, below we read a text file encoded in ISO-8859-1:

\begin{verbatim}<<>>=
x <- stri_read_lines("ES_latin1.txt", encoding="ISO-8859-1")
head(x, 4)  # x is in UTF-8 now
@\end{verbatim}


We can call \texttt{stri\_write\_lines()} to write the contents
of a character vector to a file (each string will
constitute a separate text line), with any output encoding.




\paragraph{Detecting encoding.}
However, if a file's encoding is not known in advance, there are
a certain functions that can aid in encoding detection.
First, we can read the resource in form of a raw-type vector:

% Character vectors in {R} resemble lists of raw-type vectors
% (each ended up with byte 0x00). Each string has to be properly "decoded" so that textual information may be read from such a byte stream. This "decoding scheme" is simply called a character encoding.
%
% In other words, data in computer's memory are just bytes (small integer values) – an encoding is a way to represent characters with such numbers, it is a semantic "key" to understand a given byte sequence. For example, in ISO-8859-2 (Central European), the value 177 represents Polish ``a with ogonek'', and in ISO-8859-1 (Western European), the same value meas the ``plus-minus'' sign. Thus, a character encoding is a translation scheme.

\begin{verbatim}<<>>=
x <- stri_read_raw("ES_latin1.txt")
head(x, 24)  # vector of type raw
@\end{verbatim}

Then, to guess the encoding, we can call, e.g.:

\begin{verbatim}<<>>=
stri_enc_isascii(x)
stri_enc_isutf8(x)   # false positives are possible
@\end{verbatim}

\noindent
Alternatively, we can use:

\begin{verbatim}<<>>=
stri_enc_detect(x)  # based on heuristics
@\end{verbatim}

\noindent
Nevertheless, encoding detection is an operation that relies on heuristics,
therefore there is a  chance that the output might be imprecise or even
misleading.




\paragraph{Converting encodings.}
Knowing the desired source and destination encoding precisely,
\texttt{stri\_encode()} can be called to perform the conversion.
Contrary to the built-in \texttt{iconv()}, which relies
on different underlying libraries, the current function is portable
across operating systems.


\begin{verbatim}<<>>=
y <- stri_encode(x, from="ISO-8859-1", to="UTF-8")
@\end{verbatim}

\texttt{stri\_enc\_list()}  provides a list of
supported encodings and their aliases in many different forms.
Encoding specifiers are normalised automatically, e.g.,
\texttt{"utf8"} is a synonym for \texttt{"UTF-8"}.


Splitting the output  into text lines gives:

\begin{verbatim}<<>>=
tail(stri_split_lines1(y), 4)  # spoiler alert!
@\end{verbatim}



% <<>>=
% stri_enc_info("utf8")
% @






% https://unicode-org.github.io/icu/userguide/strings/unicodeset.html
% https://unicode-org.github.io/icu/userguide/strings/properties.html



% \texttt{stri\_encode()} \texttt{to_raw=TRUE}
%
% \texttt{stri\_enc\_get()}
%
% \texttt{stri\_enc\_toascii()}
%
% \texttt{stri\_enc\_tonative()}
%
% \texttt{stri\_enc\_toutf32()}
%
% \texttt{stri\_enc\_toutf8()}
%
% \texttt{stri\_enc\_fromutf32()}
%
%
% <<>>=
% stri_enc_info("cp1250")
% @
%
%
%
%
% \texttt{stri\_encode()}
% \texttt{stri\_trans_nf*()}








\subsection{Normalising strings}\label{Sec:normalisation}

In Section~\ref{Sec:Equivalence} we have provided some examples
of canonically equivalent strings whose code point representation was different.
Unicode normalisation forms C (Canonical composition, NFC) and D
(Canonical decomposition, NFD) can be applied so that they
will compare equal using bytewise matching \citep{usa15:normalization}.

\begin{verbatim}<<>>=
x <- "a\u0328 ą"   # a, combining ogonek, space, a with ogonek
stri_enc_toutf32(  # code points as decimals
  c(x, stri_trans_nfc(x), stri_trans_nfd(x)))
@\end{verbatim}

Above we see some example code points before, after NFC,
and after NFD normalisation, respectively.

It might be a good idea to always normalise all the strings
read from external sources (files, URLs) with NFC.

Compatibility composition and decomposition normalisation forms (NFKC and
NFKD, respectively) are also available if
the removal of the formatting distinctions (font variants,
subscripts, superscripts, etc.) is desired. For example:


\begin{verbatim}<<>>=
stri_trans_nfkd("r²︷")
@\end{verbatim}

Such text might be much easier to process or analyse statistically.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% -- Summary/conclusions/discussion -------------------------------------------

\section{Closing remarks}\label{Sec:conclusions}



% Other:
%
% \texttt{stri\_stats\_general()}
% \texttt{stri\_stats\_latex()}

We have reviewed the key design principles and facilities available in
\textit{stringi}, including numerous operations
that  help implement and optimise data processing pipelines.
Let us again stress that many package features are provided by \textit{ICU}, which
is a platform-independent project. Hence, information
presented above might be of interest to statisticians and data scientists
employing different programming environments as well.



Users seeking Unicode-aware replacements for base {R}
string processing functions are kindly referred to the \textit{stringx}
package \citep{stringx}, which is a set of wrappers around \textit{stringi}
offering a more classic API
(functions such as \texttt{grepl()}, \texttt{substring()}, etc.,
compare Table~\ref{Tab:oldstringr}).


\textit{stringi} functions can also be accessed from within {C++}
code. Authors of statistical/data analysis software who would like to
speed up their projects are encouraged to check out
the \textit{ExampleRcppStringi} package available at
\url{https://github.com/gagolews/ExampleRcppStringi},
which serves as a working prototype developed using \textit{Rcpp} \citep{rcppbook}.








% TODO: check CITATION
%
% https://cran.r-project.org/web/packages/qdapRegex/index.html
% https://cran.r-project.org/web/packages/namedCapture/index.html
% https://cran.r-project.org/web/packages/rebus/index.html
% https://cran.r-project.org/web/packages/rematch2/index.html
% https://cran.r-project.org/web/packages/rex/index.html
% https://cran.r-project.org/web/packages/RVerbalExpressions/index.html
% https://cran.r-project.org/web/packages/inverseRegex/index.html
%
% other R packages TODO check CITATION
% https://cran.r-project.org/web/packages/rprintf/index.html
% https://cran.r-project.org/web/packages/ScrabbleScore/index.html
% https://cran.r-project.org/web/packages/snakecase/index.html
% https://cran.r-project.org/web/packages/strex/index.html
% https://cran.r-project.org/web/packages/stringb/index.html
% https://cran.r-project.org/web/packages/stringdist/index.html
% https://cran.r-project.org/web/packages/stringfish/index.html
% https://cran.r-project.org/web/packages/stringformattr/index.html
% https://cran.r-project.org/web/packages/textutils/index.html
% https://cran.r-project.org/web/packages/tidyselect/index.html
% https://cran.r-project.org/web/packages/tidystringdist/index.html
% https://cran.r-project.org/web/packages/unglue/index.html
% https://cran.r-project.org/web/packages/uniqtag/index.html
% https://cran.r-project.org/web/packages/yasp/index.html
% https://cran.r-project.org/web/packages/clustringr/index.html # genie supports clustering as well
% https://cran.r-project.org/web/packages/concatenate/index.html
% https://cran.r-project.org/web/packages/cwhmisc/index.html
% https://cran.r-project.org/web/packages/fansi/index.html
% https://cran.r-project.org/web/packages/filesstrings/index.html
% https://cran.r-project.org/web/packages/fuzzywuzzyR/index.html
% https://cran.r-project.org/web/packages/glue/index.html
% https://cran.r-project.org/web/packages/GrpString/index.html
% https://cran.r-project.org/web/packages/gsubfn/index.html
% https://cran.r-project.org/web/packages/mgsub/index.html
% https://cran.r-project.org/web/packages/rprintf/index.html
% and of course
% https://cran.r-project.org/web/packages/stringr/index.html






\paragraph{Future of \textit{stringi}.}
Over the years, many useful {R} packages related
to text processing have been developed, see \citep{textminingr,textr}
for some reviews.
Several of them are listed in the CRAN Task View
on Natural Language Processing\footnote{
See \url{%
https://cran.r-project.org/web/views/NaturalLanguageProcessing.html}.
}.
At the time of the writing of this paper,
\textit{stringi} itself had over 200 strong (direct) reverse dependencies
and has established itself as one of the most frequently downloaded
{R} extension. Its user base is growing steadily.

Most importantly, the package can be relied upon by other software projects
as its API is considered stable and most changes are backward compatible.

Future work will involve the porting of \textit{stringi} to different
scientific/statistical computing environments, including
{Julia} and {Python}
with the \textit{NumPy} \citep{numpy} ecosystem,
offering more Unicode-aware alternatives to the vectorised text processing
facilities from \texttt{numpy.char} and \textit{pandas} \citep[Chap.~7]{pandas}.
% PyICU

Moreover, further extensions of \textit{stringi} shall be conveyed
in order to provide an even broader coverage of \textit{ICU} services.
% including number and message formatting



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%



\section*{Acknowledgements}

\textit{stringi} is an open source project
distributed under the terms of the BSD-3-clause license.
Its most recent development snapshot is available through GitHub at
\url{https://github.com/gagolews/stringi}. The bug- and feature request
tracker can be accessed from
\url{https://github.com/gagolews/stringi/issues}.
Moreover, its homepage -- which includes a reference manual
documents the package's API in detail --
is located at \url{https://stringi.gagolewski.com/}.

The author wishes to thank Hadley Wickham for coming
up with the original \textit{stringr} package API (see Table~\ref{Tab:oldstringr}).
Also, greatly appreciated are the contributions of all who have donated their
time and effort (in all the possible forms: code, feature suggestions,
ideas, criticism, testing) to make \textit{stringi} better --
Bartek Tartanus,
Kenneth Benoit,
Marcin Bujarski,
Bill Denney,
Katrin Leinweber,
Jeroen Ooms,
Davis Vaughan,
and many others,
see \url{https://github.com/gagolews/stringi/graphs/contributors}.
More contributions are always welcome.




%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% -- Bibliography -------------------------------------------------------------
%% - References need to be provided in a .bib BibTeX database.
%% - All references should be made with \cite, \citet, \citep, \citealp etc.
%%   (and never hard-coded). See the FAQ for details.
%% - JSS-specific markup (, \textit, \texttt) should be used in the .bib.
%% - Titles in the .bib should be in title case.
%% - DOIs should be included where available.

\bibliography{bibliography}



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%




\begin{table}[p!]
\centering

\begin{tabularx}{1.0\linewidth}{p{3.4cm}p{3.7cm}X}
\toprule
\textit{stringr} 0.6.2                            & \bfseries Base {R} 4.1           & \bfseries Purpose \\
\midrule
\texttt{str\_c()}                                & \texttt{paste()}, \texttt{paste0()}, also \texttt{sprintf()}                          & join strings \\                                                          \midrule
\texttt{str\_count()}                            & \texttt{gregexpr()}                      & count pattern matches\\                                                  \midrule
\texttt{str\_detect()}                           & \texttt{grepl()}                         & detect pattern matches \\                                                \midrule
\texttt{str\_dup()}                              & \texttt{strrep()}                        & duplicate strings\\                                                      \midrule
\texttt{str\_extract()}, \texttt{str\_extract\_all()} & \texttt{regmatches()} with \texttt{regexpr()}, \texttt{gregexpr()}                                      & extract (first, all) pattern matches  \\                                 \midrule
\texttt{str\_length()}                           & \texttt{nchar()}                         & compute string length \\                                                 \midrule
                                               & \texttt{nchar(type="width")}             & compute string width \\                                                 \midrule
\texttt{str\_locate()}, \texttt{str\_locate\_all()}& \texttt{regexpr()}, \texttt{gregexpr()}    & locate (first, all) pattern matches \\                                   \midrule
\texttt{str\_match()}, \texttt{str\_match\_all()}  & \texttt{regmatches()} with \texttt{regexec()}, \texttt{gregexec()}    & extract (first, all) matches to regex capture groups \\                  \midrule
\texttt{str\_pad()}                              &                                        & add whitespaces at beginning or end\\                                    \midrule
\texttt{str\_replace()}, \texttt{str\_replace\_all()}   & \texttt{sub()}, \texttt{gsub()}       & replace (first, all) pattern matches with a replacement string\\        \midrule
\texttt{str\_split()}, \texttt{str\_split\_fixed()}& \texttt{strsplit()}                      & split up a string into  pieces \\                       \midrule
\texttt{str\_sub()}    & \texttt{substr()}, \texttt{substring()}                     & extract or replace substrings\\                                         \midrule
\texttt{str\_trim()}                             & \texttt{trimws()}                        & remove whitespaces from beginning or end \\                              \midrule
\texttt{str\_wrap()}                             & \texttt{strwrap()}                       & split strings into text lines \\                                         \midrule
\texttt{word()}                                  &                                        & extract words from a sentence \\  \midrule
                                               & \texttt{startsWith()}, \texttt{endsWith()} & determine if strings start or end with a pattern match \\ \midrule
                                               & \texttt{tolower()}, \texttt{toupper()}     & case mapping and folding \\ \midrule
                                               & \texttt{chartr()}                        & transliteration \\ \midrule
                                               & \texttt{sprintf()}                       & string formatting \\ \midrule
                                               & \texttt{strftime()}, \texttt{strptime()}   & date-time formatting and parsing \\
\bottomrule
\end{tabularx}

\caption{\label{Tab:oldstringr} Functions in (the historical)
\textit{stringr} 0.6.2 and their counterparts in base {R} 4.1.}
\end{table}


\end{document}
