#!/usr/bin/Rscript --vanilla


# ############################################################################ #
#                                                                              #
#   Converts an R package's documentation to reStructuredText (.rst)           #
#                                                                              #
#   Copyleft (C) 2020, Marek Gagolewski <https://www.gagolewski.com>           #
#                                                                              #
#                                                                              #
#   This program is free software: you can redistribute it and/or modify       #
#   it under the terms of the GNU Affero General Public License                #
#   Version 3, 19 November 2007, published by the Free Software Foundation.    #
#   This program is distributed in the hope that it will be useful,            #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the               #
#   GNU Affero General Public License Version 3 for more details.              #
#   You should have received a copy of the License along with this program.    #
#   If this is not the case, refer to <https://www.gnu.org/licenses/>.         #
#                                                                              #
# ############################################################################ #



# System requirements: R, pandoc


# I'm applying a super-lazy approach here: the complete manual bundle
# will be generated from an HTML version. tools::Rd2HTML() does a good job
# by outputting well-structured and easily-digestible source files.

# It also does cross-referencing right.

# Yet, it's far from perfect with regards to mathematical formulae.


# I have no time to implement a full-fledged parser.
# Feel free to contact me to to discuss further ideas and maybe
# we could come up with something more useful together.

# Also, it would be nice to implement a standalone Sphinx domain for R.
# See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html
# and https://www.sphinx-doc.org/en/master/extdev/domainapi.html


# Note: these HTML files are generated by a computer program.
# Hence, it is okay to process them with regexes.

# Caution: not tested on humans and other animals.


library("stringi")
cat("Rd2rst - Copyleft (C) 2020, Marek Gagolewski <https://www.gagolewski.com>\n")


if (length(commandArgs(TRUE)) != 1)
    stop("Usage: Rd2rst <package_name>")

package <- commandArgs(TRUE)[1]
library(package, character.only=TRUE)
input_path <- file.path(path.package(package), "html")

if (!file.exists(file.path(input_path, "00Index.html"))) {
    stop("HTML documentation not installed. Use `R CMD INSTALL <package_path> --html`.")
}


# Flush/recreate the output dir, which is rapi/
if (dir.exists("rapi")) {
    unlink("rapi", recursive=TRUE)
}
dir.create("rapi")

tmpname <- tempfile()

# list of inputs:
fnames <- setdiff(list.files(input_path, "\\.html$"), "00Index.html")

# process all inputs:
index <- character(0)
for (fname in fnames) {
    cat(sprintf("Converting %s...", fname))
    fhtml <- readLines(file.path(input_path, fname))

    bname <- stri_match_first_regex(fname, "(.*)\\.html")[, 2]


    stopifnot(stri_detect_regex(fhtml[6], "^<table.*</table>$"))

    stopifnot(stri_detect_regex(fhtml[8], "^<h2>.*</h2>$"))
    title <- stri_match_first_regex(fhtml[8], "^<h2>(.*)</h2>$")[, 2]

    index <- rbind(index, c(bname, title))

    fhtml[6] <- sprintf("<h1>%s: %s</h1>", bname, title)
    fhtml[8] <- ""



    # Remove link to the index page:
    stopifnot(stri_detect_fixed(fhtml[length(fhtml)-1], "00Index.html"))
    fhtml <- fhtml[-(length(fhtml)-1)]

    # Pandoc needs this to convert the links right:
    #    <code><a href="stri_datetime_add.html">stri_datetime_add</a>()</code>,
    # -> <a href="stri_datetime_add.html">stri_datetime_add()</a>,
    fhtml <- stri_replace_all_regex(fhtml, "<code><a href=\"([^./]+?\\.html)\">(.*?)</a>(.*?)</code>", "<a href=\"$1\">$2$3</a>")

    writeLines(fhtml, tmpname)


    orst <- system2("pandoc", stdout=TRUE,
        args=c("--from html", "--to rst", "--wrap=none", tmpname))
    # preformatted code blocks as R code
    orst <- stri_replace_first_regex(orst, "^::$", ".. code-block:: r")

    oname <- sprintf("rapi/%s.rst", bname)
    writeLines(orst, oname)

    cat(" done.\n")
}


rapi_index_title <- sprintf("R Package *%s* Reference", package)
rapi_index <- c(
    rapi_index_title,
    stri_dup("=", stri_length(rapi_index_title)),
    "",
    ".. toctree::",
    "    :maxdepth: 1",
    #"    :caption: API Documentation:",
    "",
    sprintf("    rapi/%s", index[, 1])
)
writeLines(rapi_index, "rapi.rst")

invisible(file.remove(tmpname))
invisible(NULL)
