#!/usr/bin/Rscript --vanilla

## Converts an R package's documentation to reStructuredText (.rst)
## Copyleft 2020, Marek Gagolewski (https://www.gagolewski.com)

# I'm applying a super-lazy approach here: the complete manual bundle
# will be generated from an HTML version. tools::Rd2HTML() does a good job
# by outputting well-structured and easily-digestible source files.

# It also does cross-referencing right.

# Yet, it's far from perfect with regards to mathematical formulae.


# I have no time to implement a full-fledged parser.
# Feel free to contact me to to discuss further ideas and maybe
# we could come up with something more useful together.

# Also, it would be nice to implement a standalone Sphinx domain for R.
# See https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html
# and https://www.sphinx-doc.org/en/master/extdev/domainapi.html


# Note: these HTML files are generated by a computer program.
# Hence, it is okay to process them with regexes.

library("stringi")



if (length(commandArgs(TRUE)) != 1)
    stop("Usage: Rd2rst <package_name>")

package <- commandArgs(TRUE)[1]
library(package, character.only=TRUE)
input_path <- file.path(path.package(package), "html")

if (!file.exists(file.path(input_path, "00Index.html"))) {
    stop("HTML documentation not installed. Use `R CMD INSTALL <package_path> --html`.")
}

if (dir.exists("rapi")) {
    unlink("rapi", recursive=TRUE)
}
dir.create("rapi")

tmpname <- tempfile()
fnames <- setdiff(list.files(input_path, "\\.html$"), "00Index.html")


for (fname in fnames) {
    cat("Converting %s...", fname)
    fhtml <- readLines(file.path(input_path, fname))

    # Remove link to the index page:
    stopifnot(stri_detect_fixed(fhtml[length(fhtml)-1], "00Index.html"))
    fhtml <- fhtml[-(length(fhtml)-1)]

    # Pandoc needs this to convert the links right:
    #    <code><a href="stri_datetime_add.html">stri_datetime_add</a>()</code>,
    # -> <a href="stri_datetime_add.html"><code>stri_datetime_add()</code></a>,
    fhtml <- stri_replace_all_regex(fhtml, "<code><a href=\"([^./]+?\\.html)\">(.*?)</a>(.*?)</code>", "<a href=\"$1\"><code>$2$3</code></a>")



    writeLines(fhtml, tmpname)


    orst <- system2("pandoc", stdout=TRUE,
        args=c("--from html", "--to rst", "--filter=Rd2rst_links_filter.py", tmpname))
    # preformatted code blocks as R code
    orst <- stri_replace_first_regex(orst, "^::$", ".. code-block:: r")

    oname <- stri_replace_first_regex(fname, "(.*)\\.html", "rapi/$1.rst")
    writeLines(orst, oname)
    cat(" done.\n", fname)
}


file.remove(tmpname)


